{"uid":"d147ea3db0edb492","name":"test__constraints_wrong_column_order","fullName":"tests.functional.adapter.test_constraints.TestIncrementalConstraintsColumnsEqualFirebolt#test__constraints_wrong_column_order","historyId":"1aa325b703ad92c0587ebb159133b2a8","time":{"start":1724321814211,"stop":1724321838206,"duration":23995},"status":"broken","statusMessage":"dbt.exceptions.DbtRuntimeError: Runtime Error\n  Runtime Error\n    Database Error\n      Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\n      For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502","statusTrace":"cls = <class 'dbt.adapters.firebolt.connections.FireboltConnectionManager'>\nconnection = Connection(type='firebolt', name='list_integration_testing__1724321556329_public', state=<ConnectionState.CLOSED: 'clo...'com.firebolt.FireboltDriver', engine_name='integration_testing__1724321556329', account_name='automation', retries=1))\nconnect = <function FireboltConnectionManager.open.<locals>.connect at 0x7ffa7146e1f0>\nlogger = AdapterLogger(name='Firebolt')\nretryable_exceptions = [<class 'firebolt.utils.exception.FireboltDatabaseError'>, <class 'firebolt.utils.exception.ConnectionError'>, <class 'firebolt.utils.exception.InterfaceError'>]\nretry_limit = 1, retry_timeout = 1, _attempts = 0\n\n    @classmethod\n    def retry_connection(\n        cls,\n        connection: Connection,\n        connect: Callable[[], AdapterHandle],\n        logger: AdapterLogger,\n        retryable_exceptions: Iterable[Type[Exception]],\n        retry_limit: int = 1,\n        retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1,\n        _attempts: int = 0,\n    ) -> Connection:\n        \"\"\"Given a Connection, set its handle by calling connect.\n    \n        The calls to connect will be retried up to retry_limit times to deal with transient\n        connection errors. By default, one retry will be attempted if retryable_exceptions is set.\n    \n        :param Connection connection: An instance of a Connection that needs a handle to be set,\n            usually when attempting to open it.\n        :param connect: A callable that returns the appropiate connection handle for a\n            given adapter. This callable will be retried retry_limit times if a subclass of any\n            Exception in retryable_exceptions is raised by connect.\n        :type connect: Callable[[], AdapterHandle]\n        :param AdapterLogger logger: A logger to emit messages on retry attempts or errors. When\n            handling expected errors, we call debug, and call warning on unexpected errors or when\n            all retry attempts have been exhausted.\n        :param retryable_exceptions: An iterable of exception classes that if raised by\n            connect should trigger a retry.\n        :type retryable_exceptions: Iterable[Type[Exception]]\n        :param int retry_limit: How many times to retry the call to connect. If this limit\n            is exceeded before a successful call, a FailedToConnectError will be raised.\n            Must be non-negative.\n        :param retry_timeout: Time to wait between attempts to connect. Can also take a\n            Callable that takes the number of attempts so far, beginning at 0, and returns an int\n            or float to be passed to time.sleep.\n        :type retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1\n        :param int _attempts: Parameter used to keep track of the number of attempts in calling the\n            connect function across recursive calls. Passed as an argument to retry_timeout if it\n            is a Callable. This parameter should not be set by the initial caller.\n        :raises dbt.exceptions.FailedToConnectError: Upon exhausting all retry attempts without\n            successfully acquiring a handle.\n        :return: The given connection with its appropriate state and handle attributes set\n            depending on whether we successfully acquired a handle or not.\n        \"\"\"\n        timeout = retry_timeout(_attempts) if callable(retry_timeout) else retry_timeout\n        if timeout < 0:\n            raise dbt.exceptions.FailedToConnectError(\n                \"retry_timeout cannot be negative or return a negative time.\"\n            )\n    \n        if retry_limit < 0 or retry_limit > sys.getrecursionlimit():\n            # This guard is not perfect others may add to the recursion limit (e.g. built-ins).\n            connection.handle = None\n            connection.state = ConnectionState.FAIL\n            raise dbt.exceptions.FailedToConnectError(\"retry_limit cannot be negative\")\n    \n        try:\n>           connection.handle = connect()\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/connections.py:241: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:121: in connect\n    handle = sdk_connect(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/connection.py:56: in connect\n    return connect_v2(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/connection.py:135: in connect_v2\n    cursor.execute(f'USE DATABASE \"{database}\"')\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/common/base_cursor.py:122: in inner\n    return func(self, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:237: in execute\n    self._do_execute(query, params_list, skip_parsing)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:186: in _do_execute\n    self._raise_if_error(resp)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:109: in _raise_if_error\n    resp.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Response [502 Bad Gateway]>\n\n    def raise_for_status(self) -> Response:\n        \"\"\"\n        Raise the `HTTPStatusError` if one occurred.\n        \"\"\"\n        request = self._request\n        if request is None:\n            raise RuntimeError(\n                \"Cannot call `raise_for_status` as the request \"\n                \"instance has not been set on this response.\"\n            )\n    \n        if self.is_success:\n            return self\n    \n        if self.has_redirect_location:\n            message = (\n                \"{error_type} '{0.status_code} {0.reason_phrase}' for url '{0.url}'\\n\"\n                \"Redirect location: '{0.headers[location]}'\\n\"\n                \"For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/{0.status_code}\"\n            )\n        else:\n            message = (\n                \"{error_type} '{0.status_code} {0.reason_phrase}' for url '{0.url}'\\n\"\n                \"For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/{0.status_code}\"\n            )\n    \n        status_class = self.status_code // 100\n        error_types = {\n            1: \"Informational response\",\n            3: \"Redirect response\",\n            4: \"Client error\",\n            5: \"Server error\",\n        }\n        error_type = error_types.get(status_class, \"Invalid status code\")\n        message = message.format(self, error_type=error_type)\n>       raise HTTPStatusError(message, request=request, response=self)\nE       httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE       For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/httpx/_models.py:761: HTTPStatusError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7ffa70082580>\nsql = '\\n\\n      SELECT\\n          table_catalog AS \"database\",\\n          table_name AS \"name\",\\n          \\'public\\' AS \"s...ofile_name\": \"test\", \"target_name\": \"default\", \"connection_name\": \"list_integration_testing__1724321556329_public\"} */'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n>           yield\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:148: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:79: in add_query\n    cursor = connection.handle.cursor()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/contracts/connection.py:90: in handle\n    self._handle.resolve(self)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/contracts/connection.py:114: in resolve\n    return self.opener(connection)\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:137: in open\n    return cls.retry_connection(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'dbt.adapters.firebolt.connections.FireboltConnectionManager'>\nconnection = Connection(type='firebolt', name='list_integration_testing__1724321556329_public', state=<ConnectionState.CLOSED: 'clo...'com.firebolt.FireboltDriver', engine_name='integration_testing__1724321556329', account_name='automation', retries=1))\nconnect = <function FireboltConnectionManager.open.<locals>.connect at 0x7ffa7146e1f0>\nlogger = AdapterLogger(name='Firebolt')\nretryable_exceptions = [<class 'firebolt.utils.exception.FireboltDatabaseError'>, <class 'firebolt.utils.exception.ConnectionError'>, <class 'firebolt.utils.exception.InterfaceError'>]\nretry_limit = 1, retry_timeout = 1, _attempts = 0\n\n    @classmethod\n    def retry_connection(\n        cls,\n        connection: Connection,\n        connect: Callable[[], AdapterHandle],\n        logger: AdapterLogger,\n        retryable_exceptions: Iterable[Type[Exception]],\n        retry_limit: int = 1,\n        retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1,\n        _attempts: int = 0,\n    ) -> Connection:\n        \"\"\"Given a Connection, set its handle by calling connect.\n    \n        The calls to connect will be retried up to retry_limit times to deal with transient\n        connection errors. By default, one retry will be attempted if retryable_exceptions is set.\n    \n        :param Connection connection: An instance of a Connection that needs a handle to be set,\n            usually when attempting to open it.\n        :param connect: A callable that returns the appropiate connection handle for a\n            given adapter. This callable will be retried retry_limit times if a subclass of any\n            Exception in retryable_exceptions is raised by connect.\n        :type connect: Callable[[], AdapterHandle]\n        :param AdapterLogger logger: A logger to emit messages on retry attempts or errors. When\n            handling expected errors, we call debug, and call warning on unexpected errors or when\n            all retry attempts have been exhausted.\n        :param retryable_exceptions: An iterable of exception classes that if raised by\n            connect should trigger a retry.\n        :type retryable_exceptions: Iterable[Type[Exception]]\n        :param int retry_limit: How many times to retry the call to connect. If this limit\n            is exceeded before a successful call, a FailedToConnectError will be raised.\n            Must be non-negative.\n        :param retry_timeout: Time to wait between attempts to connect. Can also take a\n            Callable that takes the number of attempts so far, beginning at 0, and returns an int\n            or float to be passed to time.sleep.\n        :type retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1\n        :param int _attempts: Parameter used to keep track of the number of attempts in calling the\n            connect function across recursive calls. Passed as an argument to retry_timeout if it\n            is a Callable. This parameter should not be set by the initial caller.\n        :raises dbt.exceptions.FailedToConnectError: Upon exhausting all retry attempts without\n            successfully acquiring a handle.\n        :return: The given connection with its appropriate state and handle attributes set\n            depending on whether we successfully acquired a handle or not.\n        \"\"\"\n        timeout = retry_timeout(_attempts) if callable(retry_timeout) else retry_timeout\n        if timeout < 0:\n            raise dbt.exceptions.FailedToConnectError(\n                \"retry_timeout cannot be negative or return a negative time.\"\n            )\n    \n        if retry_limit < 0 or retry_limit > sys.getrecursionlimit():\n            # This guard is not perfect others may add to the recursion limit (e.g. built-ins).\n            connection.handle = None\n            connection.state = ConnectionState.FAIL\n            raise dbt.exceptions.FailedToConnectError(\"retry_limit cannot be negative\")\n    \n        try:\n            connection.handle = connect()\n            connection.state = ConnectionState.OPEN\n            return connection\n    \n        except tuple(retryable_exceptions) as e:\n            if retry_limit <= 0:\n                connection.handle = None\n                connection.state = ConnectionState.FAIL\n                raise dbt.exceptions.FailedToConnectError(str(e))\n    \n            logger.debug(\n                f\"Got a retryable error when attempting to open a {cls.TYPE} connection.\\n\"\n                f\"{retry_limit} attempts remaining. Retrying in {timeout} seconds.\\n\"\n                f\"Error:\\n{e}\"\n            )\n    \n            sleep(timeout)\n            return cls.retry_connection(\n                connection=connection,\n                connect=connect,\n                logger=logger,\n                retry_limit=retry_limit - 1,\n                retry_timeout=retry_timeout,\n                retryable_exceptions=retryable_exceptions,\n                _attempts=_attempts + 1,\n            )\n    \n        except Exception as e:\n            connection.handle = None\n            connection.state = ConnectionState.FAIL\n>           raise dbt.exceptions.FailedToConnectError(str(e))\nE           dbt.exceptions.FailedToConnectError: Database Error\nE             Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE             For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/connections.py:271: FailedToConnectError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7ffa70082580>\nsql = 'macro list_relations_without_caching'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n>           yield\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:148: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:1112: in execute_macro\n    result = macro_function(**kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:330: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:257: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:330: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:257: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:330: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:257: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:310: in execute\n    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch, limit=limit)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:138: in execute\n    _, cursor = self.add_query(sql, auto_begin)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:90: in add_query\n    return connection, cursor\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py:137: in __exit__\n    self.gen.throw(typ, value, traceback)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7ffa70082580>\nsql = '\\n\\n      SELECT\\n          table_catalog AS \"database\",\\n          table_name AS \"name\",\\n          \\'public\\' AS \"s...ofile_name\": \"test\", \"target_name\": \"default\", \"connection_name\": \"list_integration_testing__1724321556329_public\"} */'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n            yield\n        except Exception as e:\n            self.release()\n>           raise DbtRuntimeError(str(e))\nE           dbt.exceptions.DbtRuntimeError: Runtime Error\nE             Database Error\nE               Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE               For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:151: DbtRuntimeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_constraints.TestIncrementalConstraintsColumnsEqualFirebolt object at 0x7ffa73415fa0>\nproject = <dbt.tests.fixtures.project.TestProjInfo object at 0x7ffa711087c0>\n\n    def test__constraints_wrong_column_order(self, project):\n        # This no longer causes an error, since we enforce yaml column order\n>       run_dbt([\"run\", \"-s\", \"my_model_wrong_order\"], expect_pass=True)\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/adapter/constraints/test_constraints.py:82: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/util.py:105: in run_dbt\n    raise res.exception\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:91: in wrapper\n    result, success = func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:76: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:169: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:198: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:245: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:278: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/main.py:626: in run\n    results = task.run()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/runnable.py:502: in run\n    result = self.execute_with_hooks(selected_uids)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/runnable.py:462: in execute_with_hooks\n    self.before_run(adapter, selected_uids)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/run.py:451: in before_run\n    self.populate_adapter_cache(adapter, required_schemas)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/runnable.py:440: in populate_adapter_cache\n    adapter.set_relations_cache(self.manifest)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:519: in set_relations_cache\n    self._relations_cache_for_schemas(manifest, required_schemas)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:495: in _relations_cache_for_schemas\n    for relation in future.result():\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/_base.py:439: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/_base.py:391: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/thread.py:58: in run\n    result = self.fn(*self.args, **self.kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/utils.py:471: in connected\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/impl.py:185: in list_relations_without_caching\n    results = self.execute_macro(LIST_RELATIONS_MACRO_NAME, kwargs=kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:1112: in execute_macro\n    result = macro_function(**kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py:137: in __exit__\n    self.gen.throw(typ, value, traceback)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7ffa70082580>\nsql = 'macro list_relations_without_caching'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n            yield\n        except Exception as e:\n            self.release()\n>           raise DbtRuntimeError(str(e))\nE           dbt.exceptions.DbtRuntimeError: Runtime Error\nE             Runtime Error\nE               Database Error\nE                 Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE                 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:151: DbtRuntimeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"shared_data_dir","time":{"start":1724321589759,"stop":1724321589759,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmpdir_factory","time":{"start":1724321589759,"stop":1724321589759,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"test_data_dir","time":{"start":1724321760613,"stop":1724321760613,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"project_root","time":{"start":1724321813393,"stop":1724321813393,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clean_up_logging","time":{"start":1724321813393,"stop":1724321813393,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"profiles_root","time":{"start":1724321813393,"stop":1724321813394,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"unique_schema","time":{"start":1724321813394,"stop":1724321813394,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"profiles_config_update","time":{"start":1724321813394,"stop":1724321813394,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dbt_profile_target","time":{"start":1724321813394,"stop":1724321813394,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dbt_profile_data","time":{"start":1724321813394,"stop":1724321813394,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"profiles_yml","time":{"start":1724321813394,"stop":1724321813395,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"prefix","time":{"start":1724321813394,"stop":1724321813394,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"project_config_update","time":{"start":1724321813395,"stop":1724321813395,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dbt_project_yml","time":{"start":1724321813396,"stop":1724321813396,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"selectors_yml","time":{"start":1724321813396,"stop":1724321813397,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"selectors","time":{"start":1724321813396,"stop":1724321813396,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dependencies_yml","time":{"start":1724321813396,"stop":1724321813396,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dependencies","time":{"start":1724321813396,"stop":1724321813396,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"packages_yml","time":{"start":1724321813396,"stop":1724321813396,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"packages","time":{"start":1724321813396,"stop":1724321813396,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"adapter","time":{"start":1724321813397,"stop":1724321813858,"duration":461},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"models","time":{"start":1724321813858,"stop":1724321813858,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"macros","time":{"start":1724321813858,"stop":1724321813858,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"properties","time":{"start":1724321813859,"stop":1724321813859,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"seeds","time":{"start":1724321813859,"stop":1724321813859,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tests","time":{"start":1724321813859,"stop":1724321813859,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"project_files","time":{"start":1724321813859,"stop":1724321813859,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"snapshots","time":{"start":1724321813859,"stop":1724321813859,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"analyses","time":{"start":1724321813859,"stop":1724321813859,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"test_config","time":{"start":1724321813860,"stop":1724321813860,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"project","time":{"start":1724321813860,"stop":1724321814210,"duration":350},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"logs_dir","time":{"start":1724321813860,"stop":1724321813860,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"dbt.exceptions.DbtRuntimeError: Runtime Error\n  Runtime Error\n    Database Error\n      Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\n      For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502","statusTrace":"cls = <class 'dbt.adapters.firebolt.connections.FireboltConnectionManager'>\nconnection = Connection(type='firebolt', name='list_integration_testing__1724321556329_public', state=<ConnectionState.CLOSED: 'clo...'com.firebolt.FireboltDriver', engine_name='integration_testing__1724321556329', account_name='automation', retries=1))\nconnect = <function FireboltConnectionManager.open.<locals>.connect at 0x7ffa7146e1f0>\nlogger = AdapterLogger(name='Firebolt')\nretryable_exceptions = [<class 'firebolt.utils.exception.FireboltDatabaseError'>, <class 'firebolt.utils.exception.ConnectionError'>, <class 'firebolt.utils.exception.InterfaceError'>]\nretry_limit = 1, retry_timeout = 1, _attempts = 0\n\n    @classmethod\n    def retry_connection(\n        cls,\n        connection: Connection,\n        connect: Callable[[], AdapterHandle],\n        logger: AdapterLogger,\n        retryable_exceptions: Iterable[Type[Exception]],\n        retry_limit: int = 1,\n        retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1,\n        _attempts: int = 0,\n    ) -> Connection:\n        \"\"\"Given a Connection, set its handle by calling connect.\n    \n        The calls to connect will be retried up to retry_limit times to deal with transient\n        connection errors. By default, one retry will be attempted if retryable_exceptions is set.\n    \n        :param Connection connection: An instance of a Connection that needs a handle to be set,\n            usually when attempting to open it.\n        :param connect: A callable that returns the appropiate connection handle for a\n            given adapter. This callable will be retried retry_limit times if a subclass of any\n            Exception in retryable_exceptions is raised by connect.\n        :type connect: Callable[[], AdapterHandle]\n        :param AdapterLogger logger: A logger to emit messages on retry attempts or errors. When\n            handling expected errors, we call debug, and call warning on unexpected errors or when\n            all retry attempts have been exhausted.\n        :param retryable_exceptions: An iterable of exception classes that if raised by\n            connect should trigger a retry.\n        :type retryable_exceptions: Iterable[Type[Exception]]\n        :param int retry_limit: How many times to retry the call to connect. If this limit\n            is exceeded before a successful call, a FailedToConnectError will be raised.\n            Must be non-negative.\n        :param retry_timeout: Time to wait between attempts to connect. Can also take a\n            Callable that takes the number of attempts so far, beginning at 0, and returns an int\n            or float to be passed to time.sleep.\n        :type retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1\n        :param int _attempts: Parameter used to keep track of the number of attempts in calling the\n            connect function across recursive calls. Passed as an argument to retry_timeout if it\n            is a Callable. This parameter should not be set by the initial caller.\n        :raises dbt.exceptions.FailedToConnectError: Upon exhausting all retry attempts without\n            successfully acquiring a handle.\n        :return: The given connection with its appropriate state and handle attributes set\n            depending on whether we successfully acquired a handle or not.\n        \"\"\"\n        timeout = retry_timeout(_attempts) if callable(retry_timeout) else retry_timeout\n        if timeout < 0:\n            raise dbt.exceptions.FailedToConnectError(\n                \"retry_timeout cannot be negative or return a negative time.\"\n            )\n    \n        if retry_limit < 0 or retry_limit > sys.getrecursionlimit():\n            # This guard is not perfect others may add to the recursion limit (e.g. built-ins).\n            connection.handle = None\n            connection.state = ConnectionState.FAIL\n            raise dbt.exceptions.FailedToConnectError(\"retry_limit cannot be negative\")\n    \n        try:\n>           connection.handle = connect()\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/connections.py:241: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:121: in connect\n    handle = sdk_connect(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/connection.py:56: in connect\n    return connect_v2(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/connection.py:135: in connect_v2\n    cursor.execute(f'USE DATABASE \"{database}\"')\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/common/base_cursor.py:122: in inner\n    return func(self, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:237: in execute\n    self._do_execute(query, params_list, skip_parsing)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:186: in _do_execute\n    self._raise_if_error(resp)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:109: in _raise_if_error\n    resp.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Response [502 Bad Gateway]>\n\n    def raise_for_status(self) -> Response:\n        \"\"\"\n        Raise the `HTTPStatusError` if one occurred.\n        \"\"\"\n        request = self._request\n        if request is None:\n            raise RuntimeError(\n                \"Cannot call `raise_for_status` as the request \"\n                \"instance has not been set on this response.\"\n            )\n    \n        if self.is_success:\n            return self\n    \n        if self.has_redirect_location:\n            message = (\n                \"{error_type} '{0.status_code} {0.reason_phrase}' for url '{0.url}'\\n\"\n                \"Redirect location: '{0.headers[location]}'\\n\"\n                \"For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/{0.status_code}\"\n            )\n        else:\n            message = (\n                \"{error_type} '{0.status_code} {0.reason_phrase}' for url '{0.url}'\\n\"\n                \"For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/{0.status_code}\"\n            )\n    \n        status_class = self.status_code // 100\n        error_types = {\n            1: \"Informational response\",\n            3: \"Redirect response\",\n            4: \"Client error\",\n            5: \"Server error\",\n        }\n        error_type = error_types.get(status_class, \"Invalid status code\")\n        message = message.format(self, error_type=error_type)\n>       raise HTTPStatusError(message, request=request, response=self)\nE       httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE       For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/httpx/_models.py:761: HTTPStatusError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7ffa70082580>\nsql = '\\n\\n      SELECT\\n          table_catalog AS \"database\",\\n          table_name AS \"name\",\\n          \\'public\\' AS \"s...ofile_name\": \"test\", \"target_name\": \"default\", \"connection_name\": \"list_integration_testing__1724321556329_public\"} */'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n>           yield\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:148: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:79: in add_query\n    cursor = connection.handle.cursor()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/contracts/connection.py:90: in handle\n    self._handle.resolve(self)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/contracts/connection.py:114: in resolve\n    return self.opener(connection)\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:137: in open\n    return cls.retry_connection(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'dbt.adapters.firebolt.connections.FireboltConnectionManager'>\nconnection = Connection(type='firebolt', name='list_integration_testing__1724321556329_public', state=<ConnectionState.CLOSED: 'clo...'com.firebolt.FireboltDriver', engine_name='integration_testing__1724321556329', account_name='automation', retries=1))\nconnect = <function FireboltConnectionManager.open.<locals>.connect at 0x7ffa7146e1f0>\nlogger = AdapterLogger(name='Firebolt')\nretryable_exceptions = [<class 'firebolt.utils.exception.FireboltDatabaseError'>, <class 'firebolt.utils.exception.ConnectionError'>, <class 'firebolt.utils.exception.InterfaceError'>]\nretry_limit = 1, retry_timeout = 1, _attempts = 0\n\n    @classmethod\n    def retry_connection(\n        cls,\n        connection: Connection,\n        connect: Callable[[], AdapterHandle],\n        logger: AdapterLogger,\n        retryable_exceptions: Iterable[Type[Exception]],\n        retry_limit: int = 1,\n        retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1,\n        _attempts: int = 0,\n    ) -> Connection:\n        \"\"\"Given a Connection, set its handle by calling connect.\n    \n        The calls to connect will be retried up to retry_limit times to deal with transient\n        connection errors. By default, one retry will be attempted if retryable_exceptions is set.\n    \n        :param Connection connection: An instance of a Connection that needs a handle to be set,\n            usually when attempting to open it.\n        :param connect: A callable that returns the appropiate connection handle for a\n            given adapter. This callable will be retried retry_limit times if a subclass of any\n            Exception in retryable_exceptions is raised by connect.\n        :type connect: Callable[[], AdapterHandle]\n        :param AdapterLogger logger: A logger to emit messages on retry attempts or errors. When\n            handling expected errors, we call debug, and call warning on unexpected errors or when\n            all retry attempts have been exhausted.\n        :param retryable_exceptions: An iterable of exception classes that if raised by\n            connect should trigger a retry.\n        :type retryable_exceptions: Iterable[Type[Exception]]\n        :param int retry_limit: How many times to retry the call to connect. If this limit\n            is exceeded before a successful call, a FailedToConnectError will be raised.\n            Must be non-negative.\n        :param retry_timeout: Time to wait between attempts to connect. Can also take a\n            Callable that takes the number of attempts so far, beginning at 0, and returns an int\n            or float to be passed to time.sleep.\n        :type retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1\n        :param int _attempts: Parameter used to keep track of the number of attempts in calling the\n            connect function across recursive calls. Passed as an argument to retry_timeout if it\n            is a Callable. This parameter should not be set by the initial caller.\n        :raises dbt.exceptions.FailedToConnectError: Upon exhausting all retry attempts without\n            successfully acquiring a handle.\n        :return: The given connection with its appropriate state and handle attributes set\n            depending on whether we successfully acquired a handle or not.\n        \"\"\"\n        timeout = retry_timeout(_attempts) if callable(retry_timeout) else retry_timeout\n        if timeout < 0:\n            raise dbt.exceptions.FailedToConnectError(\n                \"retry_timeout cannot be negative or return a negative time.\"\n            )\n    \n        if retry_limit < 0 or retry_limit > sys.getrecursionlimit():\n            # This guard is not perfect others may add to the recursion limit (e.g. built-ins).\n            connection.handle = None\n            connection.state = ConnectionState.FAIL\n            raise dbt.exceptions.FailedToConnectError(\"retry_limit cannot be negative\")\n    \n        try:\n            connection.handle = connect()\n            connection.state = ConnectionState.OPEN\n            return connection\n    \n        except tuple(retryable_exceptions) as e:\n            if retry_limit <= 0:\n                connection.handle = None\n                connection.state = ConnectionState.FAIL\n                raise dbt.exceptions.FailedToConnectError(str(e))\n    \n            logger.debug(\n                f\"Got a retryable error when attempting to open a {cls.TYPE} connection.\\n\"\n                f\"{retry_limit} attempts remaining. Retrying in {timeout} seconds.\\n\"\n                f\"Error:\\n{e}\"\n            )\n    \n            sleep(timeout)\n            return cls.retry_connection(\n                connection=connection,\n                connect=connect,\n                logger=logger,\n                retry_limit=retry_limit - 1,\n                retry_timeout=retry_timeout,\n                retryable_exceptions=retryable_exceptions,\n                _attempts=_attempts + 1,\n            )\n    \n        except Exception as e:\n            connection.handle = None\n            connection.state = ConnectionState.FAIL\n>           raise dbt.exceptions.FailedToConnectError(str(e))\nE           dbt.exceptions.FailedToConnectError: Database Error\nE             Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE             For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/connections.py:271: FailedToConnectError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7ffa70082580>\nsql = 'macro list_relations_without_caching'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n>           yield\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:148: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:1112: in execute_macro\n    result = macro_function(**kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:330: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:257: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:330: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:257: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:330: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:257: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:310: in execute\n    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch, limit=limit)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:138: in execute\n    _, cursor = self.add_query(sql, auto_begin)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:90: in add_query\n    return connection, cursor\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py:137: in __exit__\n    self.gen.throw(typ, value, traceback)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7ffa70082580>\nsql = '\\n\\n      SELECT\\n          table_catalog AS \"database\",\\n          table_name AS \"name\",\\n          \\'public\\' AS \"s...ofile_name\": \"test\", \"target_name\": \"default\", \"connection_name\": \"list_integration_testing__1724321556329_public\"} */'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n            yield\n        except Exception as e:\n            self.release()\n>           raise DbtRuntimeError(str(e))\nE           dbt.exceptions.DbtRuntimeError: Runtime Error\nE             Database Error\nE               Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE               For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:151: DbtRuntimeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_constraints.TestIncrementalConstraintsColumnsEqualFirebolt object at 0x7ffa73415fa0>\nproject = <dbt.tests.fixtures.project.TestProjInfo object at 0x7ffa711087c0>\n\n    def test__constraints_wrong_column_order(self, project):\n        # This no longer causes an error, since we enforce yaml column order\n>       run_dbt([\"run\", \"-s\", \"my_model_wrong_order\"], expect_pass=True)\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/adapter/constraints/test_constraints.py:82: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/util.py:105: in run_dbt\n    raise res.exception\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:91: in wrapper\n    result, success = func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:76: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:169: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:198: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:245: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:278: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/main.py:626: in run\n    results = task.run()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/runnable.py:502: in run\n    result = self.execute_with_hooks(selected_uids)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/runnable.py:462: in execute_with_hooks\n    self.before_run(adapter, selected_uids)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/run.py:451: in before_run\n    self.populate_adapter_cache(adapter, required_schemas)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/runnable.py:440: in populate_adapter_cache\n    adapter.set_relations_cache(self.manifest)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:519: in set_relations_cache\n    self._relations_cache_for_schemas(manifest, required_schemas)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:495: in _relations_cache_for_schemas\n    for relation in future.result():\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/_base.py:439: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/_base.py:391: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/thread.py:58: in run\n    result = self.fn(*self.args, **self.kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/utils.py:471: in connected\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/impl.py:185: in list_relations_without_caching\n    results = self.execute_macro(LIST_RELATIONS_MACRO_NAME, kwargs=kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:1112: in execute_macro\n    result = macro_function(**kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py:137: in __exit__\n    self.gen.throw(typ, value, traceback)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7ffa70082580>\nsql = 'macro list_relations_without_caching'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n            yield\n        except Exception as e:\n            self.release()\n>           raise DbtRuntimeError(str(e))\nE           dbt.exceptions.DbtRuntimeError: Runtime Error\nE             Runtime Error\nE               Database Error\nE                 Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE                 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:151: DbtRuntimeError","steps":[],"attachments":[{"uid":"15729c2662f0cd07","name":"log","source":"15729c2662f0cd07.txt","type":"text/plain","size":2805},{"uid":"a10e4134f5d6a5d4","name":"stdout","source":"a10e4134f5d6a5d4.txt","type":"text/plain","size":1551}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"project::0","time":{"start":1724321859668,"stop":1724321862201,"duration":2533},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"logs_dir::0","time":{"start":1724321862202,"stop":1724321862202,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"adapter::0","time":{"start":1724321862205,"stop":1724321862205,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"profiles_yml::0","time":{"start":1724321862207,"stop":1724321862207,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests.functional.adapter"},{"name":"suite","value":"test_constraints"},{"name":"subSuite","value":"TestIncrementalConstraintsColumnsEqualFirebolt"},{"name":"host","value":"fv-az1986-173"},{"name":"thread","value":"2163-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.functional.adapter.test_constraints"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"d147ea3db0edb492.json","parameterValues":[]}