
=== Test project_root: /tmp/pytest-of-runner/pytest-0/project60


Invoking dbt with ['run']
[0m16:13:27  Running with dbt=1.10.5
[0m16:13:27  Registered adapter: firebolt=1.9.4
[0m16:13:27  Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m16:13:27  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 8 unused configuration paths:
- models.base
- seeds.test
- seeds.base
- snapshots.test
- snapshots.base
- data_tests.test
- data_tests.base
- unit_tests.base
[0m16:13:27  Found 2 models, 464 macros, 1 unit test
[0m16:13:27  
[0m16:13:27  Concurrency: 1 threads (target='default')
[0m16:13:27  
[0m16:13:27  1 of 2 START sql view model my_upstream_model .................................. [RUN]
[0m16:13:27  1 of 2 OK created sql view model my_upstream_model ............................. [[32mSUCCESS[0m in 0.09s]
[0m16:13:27  2 of 2 START sql view model my_model ........................................... [RUN]
[0m16:13:27  2 of 2 OK created sql view model my_model ...................................... [[32mSUCCESS[0m in 0.09s]
[0m16:13:27  
[0m16:13:27  Finished running 2 view models in 0 hours 0 minutes and 0.31 seconds (0.31s).
[0m16:13:28  
[0m16:13:28  [32mCompleted successfully[0m
[0m16:13:28  
[0m16:13:28  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=2


Invoking dbt with ['test']
[0m16:13:28  Running with dbt=1.10.5
[0m16:13:28  Registered adapter: firebolt=1.9.4
[0m16:13:28  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 8 unused configuration paths:
- models.base
- seeds.test
- seeds.base
- snapshots.test
- snapshots.base
- data_tests.test
- data_tests.base
- unit_tests.base
[0m16:13:28  Found 2 models, 464 macros, 1 unit test
[0m16:13:28  
[0m16:13:28  Concurrency: 1 threads (target='default')
[0m16:13:28  
[0m16:13:28  1 of 1 START unit_test my_model::test_my_model ................................. [RUN]
[0m16:13:28  1 of 1 ERROR my_model::test_my_model ........................................... [[31mERROR[0m in 0.16s]
[0m16:13:28  
[0m16:13:28  Finished running 1 unit test in 0 hours 0 minutes and 0.23 seconds (0.23s).
[0m16:13:28  
[0m16:13:28  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[0m16:13:28  
[0m16:13:28  [31mFailure in unit_test test_my_model (models/unit_tests.yml)[0m
[0m16:13:28    Runtime Error in unit_test test_my_model (models/unit_tests.yml)
  An error occurred during execution of unit test 'test_my_model'. There may be an error in the unit test definition: check the data types.
   Runtime Error
    Error executing query:
    {
      "errors": [
        {
          "description": "CREATE DIMENSION TABLE AS SELECT is not supported in Firebolt Core"
        }
      ],
      "query": {
        "query_id": "936a3f2e-3d26-4561-8485-535568b08edb",
        "query_label": null,
        "request_id": "14d224a7-961f-400f-9b6d-9a2473a5fa9a"
      },
      "statistics": {
        "elapsed": 0.0
      }
    }
    
[0m16:13:28  
[0m16:13:28  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 NO-OP=0 TOTAL=1
