

Invoking dbt with ['run']
[0m13:29:17  Running with dbt=1.8.5
[0m13:29:17  Registered adapter: firebolt=1.6.4
[0m13:29:17  Found 2 models, 1 snapshot, 1 seed, 3 data tests, 1 source, 2 exposures, 448 macros
[0m13:29:17  
[0m13:29:18  Concurrency: 1 threads (target='default')
[0m13:29:18  
[0m13:29:18  1 of 2 START sql view model model .............................................. [RUN]
[0m13:29:18  1 of 2 ERROR creating sql view model model ..................................... [[31mERROR[0m in 0.55s]
[0m13:29:18  2 of 2 START sql view model second_model ....................................... [RUN]
[0m13:29:19  2 of 2 ERROR creating sql view model second_model .............................. [[31mERROR[0m in 0.56s]
[0m13:29:19  
[0m13:29:19  Finished running 2 view models in 0 hours 0 minutes and 2.16 seconds (2.16s).
[0m13:29:19  
[0m13:29:19  [31mCompleted with 2 errors and 0 warnings:[0m
[0m13:29:19  
[0m13:29:19    Runtime Error in model model (models/model.sql)
  Error executing query:
  {
    "errors": [
      {
        "description": "Line 2, Column 6: relation \"seed\" does not exist"
      }
    ],
    "query": {
      "query_id": "c41e0434-981e-4d7d-8d41-1e2c20f4feb6",
      "request_id": "9b53ddea-62f8-44e8-95f1-55835fb01241"
    },
    "statistics": {
      "elapsed": 0.0
    }
  }
  
[0m13:29:19  
[0m13:29:19    Runtime Error in model second_model (models/second_model.sql)
  Error executing query:
  {
    "errors": [
      {
        "description": "Line 2, Column 6: relation \"seed\" does not exist"
      }
    ],
    "query": {
      "query_id": "69d819a7-17b4-4259-af38-c60872315c78",
      "request_id": "34496737-bac0-4059-9d45-9a00fb05fd36"
    },
    "statistics": {
      "elapsed": 0.0
    }
  }
  
[0m13:29:19  
[0m13:29:19  Done. PASS=0 WARN=0 ERROR=2 SKIP=0 TOTAL=2
