{"uid":"a4687972bad14cf","name":"test_unit_test_data_type","fullName":"tests.functional.adapter.unit_testing.test_unit_testing.TestFireboltUnitTestingTypes#test_unit_test_data_type","historyId":"befa0c738caa43171237bee58e1dceea","time":{"start":1725454274765,"stop":1725454294419,"duration":19654},"status":"broken","statusMessage":"dbt_common.exceptions.base.DbtRuntimeError: Runtime Error\n  Runtime Error\n    Database Error\n      Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\n      For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502","statusTrace":"cls = <class 'dbt.adapters.firebolt.connections.FireboltConnectionManager'>\nconnection = Connection(type='firebolt', name='list_integration_testing__1725453494115_public', state=<ConnectionState.CLOSED: 'clo...'com.firebolt.FireboltDriver', engine_name='integration_testing__1725453494115', account_name='automation', retries=1))\nconnect = <function FireboltConnectionManager.open.<locals>.connect at 0x7f97c81179d0>\nlogger = AdapterLogger(name='Firebolt')\nretryable_exceptions = [<class 'firebolt.utils.exception.FireboltDatabaseError'>, <class 'firebolt.utils.exception.ConnectionError'>, <class 'firebolt.utils.exception.InterfaceError'>]\nretry_limit = 1, retry_timeout = 1, _attempts = 0\n\n    @classmethod\n    def retry_connection(\n        cls,\n        connection: Connection,\n        connect: Callable[[], AdapterHandle],\n        logger: AdapterLogger,\n        retryable_exceptions: Iterable[Type[Exception]],\n        retry_limit: int = 1,\n        retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1,\n        _attempts: int = 0,\n    ) -> Connection:\n        \"\"\"Given a Connection, set its handle by calling connect.\n    \n        The calls to connect will be retried up to retry_limit times to deal with transient\n        connection errors. By default, one retry will be attempted if retryable_exceptions is set.\n    \n        :param Connection connection: An instance of a Connection that needs a handle to be set,\n            usually when attempting to open it.\n        :param connect: A callable that returns the appropiate connection handle for a\n            given adapter. This callable will be retried retry_limit times if a subclass of any\n            Exception in retryable_exceptions is raised by connect.\n        :type connect: Callable[[], AdapterHandle]\n        :param AdapterLogger logger: A logger to emit messages on retry attempts or errors. When\n            handling expected errors, we call debug, and call warning on unexpected errors or when\n            all retry attempts have been exhausted.\n        :param retryable_exceptions: An iterable of exception classes that if raised by\n            connect should trigger a retry.\n        :type retryable_exceptions: Iterable[Type[Exception]]\n        :param int retry_limit: How many times to retry the call to connect. If this limit\n            is exceeded before a successful call, a FailedToConnectError will be raised.\n            Must be non-negative.\n        :param retry_timeout: Time to wait between attempts to connect. Can also take a\n            Callable that takes the number of attempts so far, beginning at 0, and returns an int\n            or float to be passed to time.sleep.\n        :type retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1\n        :param int _attempts: Parameter used to keep track of the number of attempts in calling the\n            connect function across recursive calls. Passed as an argument to retry_timeout if it\n            is a Callable. This parameter should not be set by the initial caller.\n        :raises dbt.adapters.exceptions.FailedToConnectError: Upon exhausting all retry attempts without\n            successfully acquiring a handle.\n        :return: The given connection with its appropriate state and handle attributes set\n            depending on whether we successfully acquired a handle or not.\n        \"\"\"\n        timeout = retry_timeout(_attempts) if callable(retry_timeout) else retry_timeout\n        if timeout < 0:\n            raise FailedToConnectError(\n                \"retry_timeout cannot be negative or return a negative time.\"\n            )\n    \n        if retry_limit < 0 or retry_limit > sys.getrecursionlimit():\n            # This guard is not perfect others may add to the recursion limit (e.g. built-ins).\n            connection.handle = None\n            connection.state = ConnectionState.FAIL  # type: ignore\n            raise FailedToConnectError(\"retry_limit cannot be negative\")\n    \n        try:\n>           connection.handle = connect()\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/connections.py:237: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:129: in connect\n    handle = sdk_connect(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/connection.py:56: in connect\n    return connect_v2(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/connection.py:135: in connect_v2\n    cursor.execute(f'USE DATABASE \"{database}\"')\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/common/base_cursor.py:122: in inner\n    return func(self, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:237: in execute\n    self._do_execute(query, params_list, skip_parsing)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:186: in _do_execute\n    self._raise_if_error(resp)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:109: in _raise_if_error\n    resp.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Response [502 Bad Gateway]>\n\n    def raise_for_status(self) -> Response:\n        \"\"\"\n        Raise the `HTTPStatusError` if one occurred.\n        \"\"\"\n        request = self._request\n        if request is None:\n            raise RuntimeError(\n                \"Cannot call `raise_for_status` as the request \"\n                \"instance has not been set on this response.\"\n            )\n    \n        if self.is_success:\n            return self\n    \n        if self.has_redirect_location:\n            message = (\n                \"{error_type} '{0.status_code} {0.reason_phrase}' for url '{0.url}'\\n\"\n                \"Redirect location: '{0.headers[location]}'\\n\"\n                \"For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/{0.status_code}\"\n            )\n        else:\n            message = (\n                \"{error_type} '{0.status_code} {0.reason_phrase}' for url '{0.url}'\\n\"\n                \"For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/{0.status_code}\"\n            )\n    \n        status_class = self.status_code // 100\n        error_types = {\n            1: \"Informational response\",\n            3: \"Redirect response\",\n            4: \"Client error\",\n            5: \"Server error\",\n        }\n        error_type = error_types.get(status_class, \"Invalid status code\")\n        message = message.format(self, error_type=error_type)\n>       raise HTTPStatusError(message, request=request, response=self)\nE       httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE       For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/httpx/_models.py:763: HTTPStatusError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f97ca78e160>\nsql = '\\n\\n      SELECT\\n          table_catalog AS \"database\",\\n          table_name AS \"name\",\\n          \\'public\\' AS \"s...ofile_name\": \"test\", \"target_name\": \"default\", \"connection_name\": \"list_integration_testing__1725453494115_public\"} */'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n>           yield\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:156: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:92: in add_query\n    cursor = connection.handle.cursor()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/contracts/connection.py:95: in handle\n    self._handle.resolve(self)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/contracts/connection.py:119: in resolve\n    return self.opener(connection)\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:145: in open\n    return cls.retry_connection(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'dbt.adapters.firebolt.connections.FireboltConnectionManager'>\nconnection = Connection(type='firebolt', name='list_integration_testing__1725453494115_public', state=<ConnectionState.CLOSED: 'clo...'com.firebolt.FireboltDriver', engine_name='integration_testing__1725453494115', account_name='automation', retries=1))\nconnect = <function FireboltConnectionManager.open.<locals>.connect at 0x7f97c81179d0>\nlogger = AdapterLogger(name='Firebolt')\nretryable_exceptions = [<class 'firebolt.utils.exception.FireboltDatabaseError'>, <class 'firebolt.utils.exception.ConnectionError'>, <class 'firebolt.utils.exception.InterfaceError'>]\nretry_limit = 1, retry_timeout = 1, _attempts = 0\n\n    @classmethod\n    def retry_connection(\n        cls,\n        connection: Connection,\n        connect: Callable[[], AdapterHandle],\n        logger: AdapterLogger,\n        retryable_exceptions: Iterable[Type[Exception]],\n        retry_limit: int = 1,\n        retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1,\n        _attempts: int = 0,\n    ) -> Connection:\n        \"\"\"Given a Connection, set its handle by calling connect.\n    \n        The calls to connect will be retried up to retry_limit times to deal with transient\n        connection errors. By default, one retry will be attempted if retryable_exceptions is set.\n    \n        :param Connection connection: An instance of a Connection that needs a handle to be set,\n            usually when attempting to open it.\n        :param connect: A callable that returns the appropiate connection handle for a\n            given adapter. This callable will be retried retry_limit times if a subclass of any\n            Exception in retryable_exceptions is raised by connect.\n        :type connect: Callable[[], AdapterHandle]\n        :param AdapterLogger logger: A logger to emit messages on retry attempts or errors. When\n            handling expected errors, we call debug, and call warning on unexpected errors or when\n            all retry attempts have been exhausted.\n        :param retryable_exceptions: An iterable of exception classes that if raised by\n            connect should trigger a retry.\n        :type retryable_exceptions: Iterable[Type[Exception]]\n        :param int retry_limit: How many times to retry the call to connect. If this limit\n            is exceeded before a successful call, a FailedToConnectError will be raised.\n            Must be non-negative.\n        :param retry_timeout: Time to wait between attempts to connect. Can also take a\n            Callable that takes the number of attempts so far, beginning at 0, and returns an int\n            or float to be passed to time.sleep.\n        :type retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1\n        :param int _attempts: Parameter used to keep track of the number of attempts in calling the\n            connect function across recursive calls. Passed as an argument to retry_timeout if it\n            is a Callable. This parameter should not be set by the initial caller.\n        :raises dbt.adapters.exceptions.FailedToConnectError: Upon exhausting all retry attempts without\n            successfully acquiring a handle.\n        :return: The given connection with its appropriate state and handle attributes set\n            depending on whether we successfully acquired a handle or not.\n        \"\"\"\n        timeout = retry_timeout(_attempts) if callable(retry_timeout) else retry_timeout\n        if timeout < 0:\n            raise FailedToConnectError(\n                \"retry_timeout cannot be negative or return a negative time.\"\n            )\n    \n        if retry_limit < 0 or retry_limit > sys.getrecursionlimit():\n            # This guard is not perfect others may add to the recursion limit (e.g. built-ins).\n            connection.handle = None\n            connection.state = ConnectionState.FAIL  # type: ignore\n            raise FailedToConnectError(\"retry_limit cannot be negative\")\n    \n        try:\n            connection.handle = connect()\n            connection.state = ConnectionState.OPEN  # type: ignore\n            return connection\n    \n        except tuple(retryable_exceptions) as e:\n            if retry_limit <= 0:\n                connection.handle = None\n                connection.state = ConnectionState.FAIL  # type: ignore\n                raise FailedToConnectError(str(e))\n    \n            logger.debug(\n                f\"Got a retryable error when attempting to open a {cls.TYPE} connection.\\n\"\n                f\"{retry_limit} attempts remaining. Retrying in {timeout} seconds.\\n\"\n                f\"Error:\\n{e}\"\n            )\n    \n            sleep(timeout)\n            return cls.retry_connection(\n                connection=connection,\n                connect=connect,\n                logger=logger,\n                retry_limit=retry_limit - 1,\n                retry_timeout=retry_timeout,\n                retryable_exceptions=retryable_exceptions,\n                _attempts=_attempts + 1,\n            )\n    \n        except Exception as e:\n            connection.handle = None\n            connection.state = ConnectionState.FAIL  # type: ignore\n>           raise FailedToConnectError(str(e))\nE           dbt.adapters.exceptions.connection.FailedToConnectError: Database Error\nE             Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE             For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/connections.py:267: FailedToConnectError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f97ca78e160>\nsql = 'macro list_relations_without_caching'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n>           yield\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:156: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:1131: in execute_macro\n    result = macro_function(**kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt_common/clients/jinja.py:335: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt_common/clients/jinja.py:298: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:84: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt_common/clients/jinja.py:298: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:84: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt_common/clients/jinja.py:298: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:356: in execute\n    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch, limit=limit)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:154: in execute\n    _, cursor = self.add_query(sql, auto_begin)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:103: in add_query\n    return connection, cursor\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py:137: in __exit__\n    self.gen.throw(typ, value, traceback)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f97ca78e160>\nsql = '\\n\\n      SELECT\\n          table_catalog AS \"database\",\\n          table_name AS \"name\",\\n          \\'public\\' AS \"s...ofile_name\": \"test\", \"target_name\": \"default\", \"connection_name\": \"list_integration_testing__1725453494115_public\"} */'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n            yield\n        except Exception as e:\n            self.release()\n>           raise DbtRuntimeError(str(e))\nE           dbt_common.exceptions.base.DbtRuntimeError: Runtime Error\nE             Database Error\nE               Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE               For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:159: DbtRuntimeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_unit_testing.TestFireboltUnitTestingTypes object at 0x7f97c9277670>\nproject = <dbt.tests.fixtures.project.TestProjInfo object at 0x7f97c64f9e50>\ndata_types = [['1', '1'], [\"'1'\", '1'], ['true', 'true'], [\"DATE '2020-01-02'\", '2020-01-02'], [\"TIMESTAMP '2013-11-03 00:00:00'\", '2013-11-03 00:00:00'], [\"TIMESTAMPTZ '2013-11-03 00:00:00-0'\", '2013-11-03 00:00:00-0'], ...]\n\n    def test_unit_test_data_type(self, project, data_types):\n        for sql_value, yaml_value in data_types:\n            # Write parametrized type value to sql files\n            write_file(\n                my_upstream_model_sql.format(sql_value=sql_value),\n                \"models\",\n                \"my_upstream_model.sql\",\n            )\n    \n            # Write parametrized type value to unit test yaml definition\n            write_file(\n                test_my_model_yml.format(yaml_value=yaml_value),\n                \"models\",\n                \"schema.yml\",\n            )\n    \n>           results = run_dbt([\"run\", \"--select\", \"my_upstream_model\"])\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/adapter/unit_testing/test_types.py:74: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/util.py:107: in run_dbt\n    raise res.exception\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:138: in wrapper\n    result, success = func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:101: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:218: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:247: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:294: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:332: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/main.py:569: in run\n    results = task.run()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/runnable.py:526: in run\n    result = self.execute_with_hooks(selected_uids)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/runnable.py:486: in execute_with_hooks\n    self.before_run(adapter, selected_uids)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/run.py:460: in before_run\n    self.populate_adapter_cache(adapter, required_schemas)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/runnable.py:464: in populate_adapter_cache\n    adapter.set_relations_cache(cachable_nodes)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:529: in set_relations_cache\n    self._relations_cache_for_schemas(relation_configs, required_schemas)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:505: in _relations_cache_for_schemas\n    for relation in future.result():\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/_base.py:439: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/_base.py:391: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/thread.py:58: in run\n    result = self.fn(*self.args, **self.kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt_common/utils/executor.py:16: in connected\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/impl.py:188: in list_relations_without_caching\n    results = self.execute_macro(LIST_RELATIONS_MACRO_NAME, kwargs=kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:1131: in execute_macro\n    result = macro_function(**kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py:137: in __exit__\n    self.gen.throw(typ, value, traceback)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f97ca78e160>\nsql = 'macro list_relations_without_caching'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n            yield\n        except Exception as e:\n            self.release()\n>           raise DbtRuntimeError(str(e))\nE           dbt_common.exceptions.base.DbtRuntimeError: Runtime Error\nE             Runtime Error\nE               Database Error\nE                 Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE                 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:159: DbtRuntimeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"tmpdir_factory","time":{"start":1725453534171,"stop":1725453534171,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"shared_data_dir","time":{"start":1725453534171,"stop":1725453534171,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"test_data_dir","time":{"start":1725454258578,"stop":1725454258578,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"environment","time":{"start":1725454274397,"stop":1725454274397,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"initialization","time":{"start":1725454274397,"stop":1725454274398,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"project_root","time":{"start":1725454274398,"stop":1725454274398,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"profiles_root","time":{"start":1725454274398,"stop":1725454274399,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clean_up_logging","time":{"start":1725454274398,"stop":1725454274398,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"prefix","time":{"start":1725454274399,"stop":1725454274399,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"unique_schema","time":{"start":1725454274399,"stop":1725454274399,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dbt_profile_data","time":{"start":1725454274399,"stop":1725454274400,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"profiles_config_update","time":{"start":1725454274399,"stop":1725454274399,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dbt_profile_target","time":{"start":1725454274399,"stop":1725454274399,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"profiles_yml","time":{"start":1725454274400,"stop":1725454274401,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dbt_project_yml","time":{"start":1725454274401,"stop":1725454274401,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"packages","time":{"start":1725454274401,"stop":1725454274401,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"project_config_update","time":{"start":1725454274401,"stop":1725454274401,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dependencies","time":{"start":1725454274401,"stop":1725454274401,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"packages_yml","time":{"start":1725454274401,"stop":1725454274401,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"selectors_yml","time":{"start":1725454274402,"stop":1725454274402,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dependencies_yml","time":{"start":1725454274402,"stop":1725454274402,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"logs_dir","time":{"start":1725454274402,"stop":1725454274402,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"adapter","time":{"start":1725454274402,"stop":1725454274429,"duration":27},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"selectors","time":{"start":1725454274402,"stop":1725454274402,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"project_files","time":{"start":1725454274430,"stop":1725454274431,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"snapshots","time":{"start":1725454274430,"stop":1725454274430,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"properties","time":{"start":1725454274430,"stop":1725454274430,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"models","time":{"start":1725454274430,"stop":1725454274430,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tests","time":{"start":1725454274430,"stop":1725454274430,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"macros","time":{"start":1725454274430,"stop":1725454274430,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"seeds","time":{"start":1725454274430,"stop":1725454274430,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"analyses","time":{"start":1725454274430,"stop":1725454274430,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"project","time":{"start":1725454274431,"stop":1725454274764,"duration":333},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"test_config","time":{"start":1725454274431,"stop":1725454274431,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"data_types","time":{"start":1725454274765,"stop":1725454274765,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"dbt_common.exceptions.base.DbtRuntimeError: Runtime Error\n  Runtime Error\n    Database Error\n      Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\n      For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502","statusTrace":"cls = <class 'dbt.adapters.firebolt.connections.FireboltConnectionManager'>\nconnection = Connection(type='firebolt', name='list_integration_testing__1725453494115_public', state=<ConnectionState.CLOSED: 'clo...'com.firebolt.FireboltDriver', engine_name='integration_testing__1725453494115', account_name='automation', retries=1))\nconnect = <function FireboltConnectionManager.open.<locals>.connect at 0x7f97c81179d0>\nlogger = AdapterLogger(name='Firebolt')\nretryable_exceptions = [<class 'firebolt.utils.exception.FireboltDatabaseError'>, <class 'firebolt.utils.exception.ConnectionError'>, <class 'firebolt.utils.exception.InterfaceError'>]\nretry_limit = 1, retry_timeout = 1, _attempts = 0\n\n    @classmethod\n    def retry_connection(\n        cls,\n        connection: Connection,\n        connect: Callable[[], AdapterHandle],\n        logger: AdapterLogger,\n        retryable_exceptions: Iterable[Type[Exception]],\n        retry_limit: int = 1,\n        retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1,\n        _attempts: int = 0,\n    ) -> Connection:\n        \"\"\"Given a Connection, set its handle by calling connect.\n    \n        The calls to connect will be retried up to retry_limit times to deal with transient\n        connection errors. By default, one retry will be attempted if retryable_exceptions is set.\n    \n        :param Connection connection: An instance of a Connection that needs a handle to be set,\n            usually when attempting to open it.\n        :param connect: A callable that returns the appropiate connection handle for a\n            given adapter. This callable will be retried retry_limit times if a subclass of any\n            Exception in retryable_exceptions is raised by connect.\n        :type connect: Callable[[], AdapterHandle]\n        :param AdapterLogger logger: A logger to emit messages on retry attempts or errors. When\n            handling expected errors, we call debug, and call warning on unexpected errors or when\n            all retry attempts have been exhausted.\n        :param retryable_exceptions: An iterable of exception classes that if raised by\n            connect should trigger a retry.\n        :type retryable_exceptions: Iterable[Type[Exception]]\n        :param int retry_limit: How many times to retry the call to connect. If this limit\n            is exceeded before a successful call, a FailedToConnectError will be raised.\n            Must be non-negative.\n        :param retry_timeout: Time to wait between attempts to connect. Can also take a\n            Callable that takes the number of attempts so far, beginning at 0, and returns an int\n            or float to be passed to time.sleep.\n        :type retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1\n        :param int _attempts: Parameter used to keep track of the number of attempts in calling the\n            connect function across recursive calls. Passed as an argument to retry_timeout if it\n            is a Callable. This parameter should not be set by the initial caller.\n        :raises dbt.adapters.exceptions.FailedToConnectError: Upon exhausting all retry attempts without\n            successfully acquiring a handle.\n        :return: The given connection with its appropriate state and handle attributes set\n            depending on whether we successfully acquired a handle or not.\n        \"\"\"\n        timeout = retry_timeout(_attempts) if callable(retry_timeout) else retry_timeout\n        if timeout < 0:\n            raise FailedToConnectError(\n                \"retry_timeout cannot be negative or return a negative time.\"\n            )\n    \n        if retry_limit < 0 or retry_limit > sys.getrecursionlimit():\n            # This guard is not perfect others may add to the recursion limit (e.g. built-ins).\n            connection.handle = None\n            connection.state = ConnectionState.FAIL  # type: ignore\n            raise FailedToConnectError(\"retry_limit cannot be negative\")\n    \n        try:\n>           connection.handle = connect()\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/connections.py:237: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:129: in connect\n    handle = sdk_connect(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/connection.py:56: in connect\n    return connect_v2(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/connection.py:135: in connect_v2\n    cursor.execute(f'USE DATABASE \"{database}\"')\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/common/base_cursor.py:122: in inner\n    return func(self, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:237: in execute\n    self._do_execute(query, params_list, skip_parsing)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:186: in _do_execute\n    self._raise_if_error(resp)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:109: in _raise_if_error\n    resp.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Response [502 Bad Gateway]>\n\n    def raise_for_status(self) -> Response:\n        \"\"\"\n        Raise the `HTTPStatusError` if one occurred.\n        \"\"\"\n        request = self._request\n        if request is None:\n            raise RuntimeError(\n                \"Cannot call `raise_for_status` as the request \"\n                \"instance has not been set on this response.\"\n            )\n    \n        if self.is_success:\n            return self\n    \n        if self.has_redirect_location:\n            message = (\n                \"{error_type} '{0.status_code} {0.reason_phrase}' for url '{0.url}'\\n\"\n                \"Redirect location: '{0.headers[location]}'\\n\"\n                \"For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/{0.status_code}\"\n            )\n        else:\n            message = (\n                \"{error_type} '{0.status_code} {0.reason_phrase}' for url '{0.url}'\\n\"\n                \"For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/{0.status_code}\"\n            )\n    \n        status_class = self.status_code // 100\n        error_types = {\n            1: \"Informational response\",\n            3: \"Redirect response\",\n            4: \"Client error\",\n            5: \"Server error\",\n        }\n        error_type = error_types.get(status_class, \"Invalid status code\")\n        message = message.format(self, error_type=error_type)\n>       raise HTTPStatusError(message, request=request, response=self)\nE       httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE       For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/httpx/_models.py:763: HTTPStatusError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f97ca78e160>\nsql = '\\n\\n      SELECT\\n          table_catalog AS \"database\",\\n          table_name AS \"name\",\\n          \\'public\\' AS \"s...ofile_name\": \"test\", \"target_name\": \"default\", \"connection_name\": \"list_integration_testing__1725453494115_public\"} */'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n>           yield\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:156: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:92: in add_query\n    cursor = connection.handle.cursor()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/contracts/connection.py:95: in handle\n    self._handle.resolve(self)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/contracts/connection.py:119: in resolve\n    return self.opener(connection)\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:145: in open\n    return cls.retry_connection(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'dbt.adapters.firebolt.connections.FireboltConnectionManager'>\nconnection = Connection(type='firebolt', name='list_integration_testing__1725453494115_public', state=<ConnectionState.CLOSED: 'clo...'com.firebolt.FireboltDriver', engine_name='integration_testing__1725453494115', account_name='automation', retries=1))\nconnect = <function FireboltConnectionManager.open.<locals>.connect at 0x7f97c81179d0>\nlogger = AdapterLogger(name='Firebolt')\nretryable_exceptions = [<class 'firebolt.utils.exception.FireboltDatabaseError'>, <class 'firebolt.utils.exception.ConnectionError'>, <class 'firebolt.utils.exception.InterfaceError'>]\nretry_limit = 1, retry_timeout = 1, _attempts = 0\n\n    @classmethod\n    def retry_connection(\n        cls,\n        connection: Connection,\n        connect: Callable[[], AdapterHandle],\n        logger: AdapterLogger,\n        retryable_exceptions: Iterable[Type[Exception]],\n        retry_limit: int = 1,\n        retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1,\n        _attempts: int = 0,\n    ) -> Connection:\n        \"\"\"Given a Connection, set its handle by calling connect.\n    \n        The calls to connect will be retried up to retry_limit times to deal with transient\n        connection errors. By default, one retry will be attempted if retryable_exceptions is set.\n    \n        :param Connection connection: An instance of a Connection that needs a handle to be set,\n            usually when attempting to open it.\n        :param connect: A callable that returns the appropiate connection handle for a\n            given adapter. This callable will be retried retry_limit times if a subclass of any\n            Exception in retryable_exceptions is raised by connect.\n        :type connect: Callable[[], AdapterHandle]\n        :param AdapterLogger logger: A logger to emit messages on retry attempts or errors. When\n            handling expected errors, we call debug, and call warning on unexpected errors or when\n            all retry attempts have been exhausted.\n        :param retryable_exceptions: An iterable of exception classes that if raised by\n            connect should trigger a retry.\n        :type retryable_exceptions: Iterable[Type[Exception]]\n        :param int retry_limit: How many times to retry the call to connect. If this limit\n            is exceeded before a successful call, a FailedToConnectError will be raised.\n            Must be non-negative.\n        :param retry_timeout: Time to wait between attempts to connect. Can also take a\n            Callable that takes the number of attempts so far, beginning at 0, and returns an int\n            or float to be passed to time.sleep.\n        :type retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1\n        :param int _attempts: Parameter used to keep track of the number of attempts in calling the\n            connect function across recursive calls. Passed as an argument to retry_timeout if it\n            is a Callable. This parameter should not be set by the initial caller.\n        :raises dbt.adapters.exceptions.FailedToConnectError: Upon exhausting all retry attempts without\n            successfully acquiring a handle.\n        :return: The given connection with its appropriate state and handle attributes set\n            depending on whether we successfully acquired a handle or not.\n        \"\"\"\n        timeout = retry_timeout(_attempts) if callable(retry_timeout) else retry_timeout\n        if timeout < 0:\n            raise FailedToConnectError(\n                \"retry_timeout cannot be negative or return a negative time.\"\n            )\n    \n        if retry_limit < 0 or retry_limit > sys.getrecursionlimit():\n            # This guard is not perfect others may add to the recursion limit (e.g. built-ins).\n            connection.handle = None\n            connection.state = ConnectionState.FAIL  # type: ignore\n            raise FailedToConnectError(\"retry_limit cannot be negative\")\n    \n        try:\n            connection.handle = connect()\n            connection.state = ConnectionState.OPEN  # type: ignore\n            return connection\n    \n        except tuple(retryable_exceptions) as e:\n            if retry_limit <= 0:\n                connection.handle = None\n                connection.state = ConnectionState.FAIL  # type: ignore\n                raise FailedToConnectError(str(e))\n    \n            logger.debug(\n                f\"Got a retryable error when attempting to open a {cls.TYPE} connection.\\n\"\n                f\"{retry_limit} attempts remaining. Retrying in {timeout} seconds.\\n\"\n                f\"Error:\\n{e}\"\n            )\n    \n            sleep(timeout)\n            return cls.retry_connection(\n                connection=connection,\n                connect=connect,\n                logger=logger,\n                retry_limit=retry_limit - 1,\n                retry_timeout=retry_timeout,\n                retryable_exceptions=retryable_exceptions,\n                _attempts=_attempts + 1,\n            )\n    \n        except Exception as e:\n            connection.handle = None\n            connection.state = ConnectionState.FAIL  # type: ignore\n>           raise FailedToConnectError(str(e))\nE           dbt.adapters.exceptions.connection.FailedToConnectError: Database Error\nE             Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE             For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/connections.py:267: FailedToConnectError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f97ca78e160>\nsql = 'macro list_relations_without_caching'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n>           yield\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:156: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:1131: in execute_macro\n    result = macro_function(**kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt_common/clients/jinja.py:335: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt_common/clients/jinja.py:298: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:84: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt_common/clients/jinja.py:298: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:84: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt_common/clients/jinja.py:298: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:356: in execute\n    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch, limit=limit)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:154: in execute\n    _, cursor = self.add_query(sql, auto_begin)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:103: in add_query\n    return connection, cursor\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py:137: in __exit__\n    self.gen.throw(typ, value, traceback)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f97ca78e160>\nsql = '\\n\\n      SELECT\\n          table_catalog AS \"database\",\\n          table_name AS \"name\",\\n          \\'public\\' AS \"s...ofile_name\": \"test\", \"target_name\": \"default\", \"connection_name\": \"list_integration_testing__1725453494115_public\"} */'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n            yield\n        except Exception as e:\n            self.release()\n>           raise DbtRuntimeError(str(e))\nE           dbt_common.exceptions.base.DbtRuntimeError: Runtime Error\nE             Database Error\nE               Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE               For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:159: DbtRuntimeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_unit_testing.TestFireboltUnitTestingTypes object at 0x7f97c9277670>\nproject = <dbt.tests.fixtures.project.TestProjInfo object at 0x7f97c64f9e50>\ndata_types = [['1', '1'], [\"'1'\", '1'], ['true', 'true'], [\"DATE '2020-01-02'\", '2020-01-02'], [\"TIMESTAMP '2013-11-03 00:00:00'\", '2013-11-03 00:00:00'], [\"TIMESTAMPTZ '2013-11-03 00:00:00-0'\", '2013-11-03 00:00:00-0'], ...]\n\n    def test_unit_test_data_type(self, project, data_types):\n        for sql_value, yaml_value in data_types:\n            # Write parametrized type value to sql files\n            write_file(\n                my_upstream_model_sql.format(sql_value=sql_value),\n                \"models\",\n                \"my_upstream_model.sql\",\n            )\n    \n            # Write parametrized type value to unit test yaml definition\n            write_file(\n                test_my_model_yml.format(yaml_value=yaml_value),\n                \"models\",\n                \"schema.yml\",\n            )\n    \n>           results = run_dbt([\"run\", \"--select\", \"my_upstream_model\"])\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/adapter/unit_testing/test_types.py:74: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/util.py:107: in run_dbt\n    raise res.exception\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:138: in wrapper\n    result, success = func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:101: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:218: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:247: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:294: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/requires.py:332: in wrapper\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/cli/main.py:569: in run\n    results = task.run()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/runnable.py:526: in run\n    result = self.execute_with_hooks(selected_uids)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/runnable.py:486: in execute_with_hooks\n    self.before_run(adapter, selected_uids)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/run.py:460: in before_run\n    self.populate_adapter_cache(adapter, required_schemas)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/task/runnable.py:464: in populate_adapter_cache\n    adapter.set_relations_cache(cachable_nodes)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:529: in set_relations_cache\n    self._relations_cache_for_schemas(relation_configs, required_schemas)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:505: in _relations_cache_for_schemas\n    for relation in future.result():\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/_base.py:439: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/_base.py:391: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/concurrent/futures/thread.py:58: in run\n    result = self.fn(*self.args, **self.kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt_common/utils/executor.py:16: in connected\n    return func(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/impl.py:188: in list_relations_without_caching\n    results = self.execute_macro(LIST_RELATIONS_MACRO_NAME, kwargs=kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:1131: in execute_macro\n    result = macro_function(**kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py:137: in __exit__\n    self.gen.throw(typ, value, traceback)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f97ca78e160>\nsql = 'macro list_relations_without_caching'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n            yield\n        except Exception as e:\n            self.release()\n>           raise DbtRuntimeError(str(e))\nE           dbt_common.exceptions.base.DbtRuntimeError: Runtime Error\nE             Runtime Error\nE               Database Error\nE                 Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?output_format=JSON_Compact'\nE                 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/home/runner/work/dbt-firebolt/dbt-firebolt/dbt/adapters/firebolt/connections.py:159: DbtRuntimeError","steps":[],"attachments":[{"uid":"4177a32658ecd29f","name":"log","source":"4177a32658ecd29f.txt","type":"text/plain","size":54797},{"uid":"27509ebe2b170b83","name":"stdout","source":"27509ebe2b170b83.txt","type":"text/plain","size":8237}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"project::0","time":{"start":1725454294906,"stop":1725454298306,"duration":3400},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"adapter::0","time":{"start":1725454298308,"stop":1725454298308,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"logs_dir::0","time":{"start":1725454298309,"stop":1725454298309,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"profiles_yml::0","time":{"start":1725454298311,"stop":1725454298311,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests.functional.adapter.unit_testing"},{"name":"suite","value":"test_unit_testing"},{"name":"subSuite","value":"TestFireboltUnitTestingTypes"},{"name":"host","value":"fv-az1433-945"},{"name":"thread","value":"2277-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.functional.adapter.unit_testing.test_unit_testing"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"a4687972bad14cf.json","parameterValues":[]}