{"uid":"578ea9ee55bde58c","name":"test_build_assert_equal","fullName":"tests.functional.adapter.utils.test_utils.TestSafeCast#test_build_assert_equal","historyId":"8e21713aff6e0a37a7382fc9b7963d22","time":{"start":1722522695966,"stop":1722522695966,"duration":0},"status":"broken","statusMessage":"dbt.exceptions.DbtRuntimeError: Runtime Error\n  Runtime Error\n    Database Error\n      Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?database=integration_testing__1722521167148&output_format=JSON_Compact'\n      For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502","statusTrace":"cls = <class 'dbt.adapters.firebolt.connections.FireboltConnectionManager'>\nconnection = Connection(type='firebolt', name='_test', state=<ConnectionState.CLOSED: 'closed'>, transaction_open=False, _handle=No...'com.firebolt.FireboltDriver', engine_name='integration_testing__1722521167148', account_name='automation', retries=1))\nconnect = <function FireboltConnectionManager.open.<locals>.connect at 0x7f53bc6b2c10>\nlogger = AdapterLogger(name='Firebolt')\nretryable_exceptions = [<class 'firebolt.utils.exception.FireboltDatabaseError'>, <class 'firebolt.utils.exception.ConnectionError'>, <class 'firebolt.utils.exception.InterfaceError'>]\nretry_limit = 1, retry_timeout = 1, _attempts = 0\n\n    @classmethod\n    def retry_connection(\n        cls,\n        connection: Connection,\n        connect: Callable[[], AdapterHandle],\n        logger: AdapterLogger,\n        retryable_exceptions: Iterable[Type[Exception]],\n        retry_limit: int = 1,\n        retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1,\n        _attempts: int = 0,\n    ) -> Connection:\n        \"\"\"Given a Connection, set its handle by calling connect.\n    \n        The calls to connect will be retried up to retry_limit times to deal with transient\n        connection errors. By default, one retry will be attempted if retryable_exceptions is set.\n    \n        :param Connection connection: An instance of a Connection that needs a handle to be set,\n            usually when attempting to open it.\n        :param connect: A callable that returns the appropiate connection handle for a\n            given adapter. This callable will be retried retry_limit times if a subclass of any\n            Exception in retryable_exceptions is raised by connect.\n        :type connect: Callable[[], AdapterHandle]\n        :param AdapterLogger logger: A logger to emit messages on retry attempts or errors. When\n            handling expected errors, we call debug, and call warning on unexpected errors or when\n            all retry attempts have been exhausted.\n        :param retryable_exceptions: An iterable of exception classes that if raised by\n            connect should trigger a retry.\n        :type retryable_exceptions: Iterable[Type[Exception]]\n        :param int retry_limit: How many times to retry the call to connect. If this limit\n            is exceeded before a successful call, a FailedToConnectError will be raised.\n            Must be non-negative.\n        :param retry_timeout: Time to wait between attempts to connect. Can also take a\n            Callable that takes the number of attempts so far, beginning at 0, and returns an int\n            or float to be passed to time.sleep.\n        :type retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1\n        :param int _attempts: Parameter used to keep track of the number of attempts in calling the\n            connect function across recursive calls. Passed as an argument to retry_timeout if it\n            is a Callable. This parameter should not be set by the initial caller.\n        :raises dbt.exceptions.FailedToConnectError: Upon exhausting all retry attempts without\n            successfully acquiring a handle.\n        :return: The given connection with its appropriate state and handle attributes set\n            depending on whether we successfully acquired a handle or not.\n        \"\"\"\n        timeout = retry_timeout(_attempts) if callable(retry_timeout) else retry_timeout\n        if timeout < 0:\n            raise dbt.exceptions.FailedToConnectError(\n                \"retry_timeout cannot be negative or return a negative time.\"\n            )\n    \n        if retry_limit < 0 or retry_limit > sys.getrecursionlimit():\n            # This guard is not perfect others may add to the recursion limit (e.g. built-ins).\n            connection.handle = None\n            connection.state = ConnectionState.FAIL\n            raise dbt.exceptions.FailedToConnectError(\"retry_limit cannot be negative\")\n    \n        try:\n>           connection.handle = connect()\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/connections.py:241: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/firebolt/connections.py:121: in connect\n    handle = sdk_connect(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/connection.py:56: in connect\n    return connect_v2(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/connection.py:139: in connect_v2\n    cursor.execute(f\"USE DATABASE {database}\")\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/common/base_cursor.py:122: in inner\n    return func(self, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:239: in execute\n    self._do_execute(query, params_list, skip_parsing)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:188: in _do_execute\n    self._raise_if_error(resp)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:110: in _raise_if_error\n    resp.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Response [502 Bad Gateway]>\n\n    def raise_for_status(self) -> Response:\n        \"\"\"\n        Raise the `HTTPStatusError` if one occurred.\n        \"\"\"\n        request = self._request\n        if request is None:\n            raise RuntimeError(\n                \"Cannot call `raise_for_status` as the request \"\n                \"instance has not been set on this response.\"\n            )\n    \n        if self.is_success:\n            return self\n    \n        if self.has_redirect_location:\n            message = (\n                \"{error_type} '{0.status_code} {0.reason_phrase}' for url '{0.url}'\\n\"\n                \"Redirect location: '{0.headers[location]}'\\n\"\n                \"For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/{0.status_code}\"\n            )\n        else:\n            message = (\n                \"{error_type} '{0.status_code} {0.reason_phrase}' for url '{0.url}'\\n\"\n                \"For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/{0.status_code}\"\n            )\n    \n        status_class = self.status_code // 100\n        error_types = {\n            1: \"Informational response\",\n            3: \"Redirect response\",\n            4: \"Client error\",\n            5: \"Server error\",\n        }\n        error_type = error_types.get(status_class, \"Invalid status code\")\n        message = message.format(self, error_type=error_type)\n>       raise HTTPStatusError(message, request=request, response=self)\nE       httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?database=integration_testing__1722521167148&output_format=JSON_Compact'\nE       For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/httpx/_models.py:761: HTTPStatusError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f53bdb5ed30>\nsql = \"\\n\\n      SELECT 'create_schema'\\n  \"\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n>           yield\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/firebolt/connections.py:148: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:79: in add_query\n    cursor = connection.handle.cursor()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/contracts/connection.py:90: in handle\n    self._handle.resolve(self)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/contracts/connection.py:114: in resolve\n    return self.opener(connection)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/firebolt/connections.py:137: in open\n    return cls.retry_connection(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'dbt.adapters.firebolt.connections.FireboltConnectionManager'>\nconnection = Connection(type='firebolt', name='_test', state=<ConnectionState.CLOSED: 'closed'>, transaction_open=False, _handle=No...'com.firebolt.FireboltDriver', engine_name='integration_testing__1722521167148', account_name='automation', retries=1))\nconnect = <function FireboltConnectionManager.open.<locals>.connect at 0x7f53bc6b2c10>\nlogger = AdapterLogger(name='Firebolt')\nretryable_exceptions = [<class 'firebolt.utils.exception.FireboltDatabaseError'>, <class 'firebolt.utils.exception.ConnectionError'>, <class 'firebolt.utils.exception.InterfaceError'>]\nretry_limit = 1, retry_timeout = 1, _attempts = 0\n\n    @classmethod\n    def retry_connection(\n        cls,\n        connection: Connection,\n        connect: Callable[[], AdapterHandle],\n        logger: AdapterLogger,\n        retryable_exceptions: Iterable[Type[Exception]],\n        retry_limit: int = 1,\n        retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1,\n        _attempts: int = 0,\n    ) -> Connection:\n        \"\"\"Given a Connection, set its handle by calling connect.\n    \n        The calls to connect will be retried up to retry_limit times to deal with transient\n        connection errors. By default, one retry will be attempted if retryable_exceptions is set.\n    \n        :param Connection connection: An instance of a Connection that needs a handle to be set,\n            usually when attempting to open it.\n        :param connect: A callable that returns the appropiate connection handle for a\n            given adapter. This callable will be retried retry_limit times if a subclass of any\n            Exception in retryable_exceptions is raised by connect.\n        :type connect: Callable[[], AdapterHandle]\n        :param AdapterLogger logger: A logger to emit messages on retry attempts or errors. When\n            handling expected errors, we call debug, and call warning on unexpected errors or when\n            all retry attempts have been exhausted.\n        :param retryable_exceptions: An iterable of exception classes that if raised by\n            connect should trigger a retry.\n        :type retryable_exceptions: Iterable[Type[Exception]]\n        :param int retry_limit: How many times to retry the call to connect. If this limit\n            is exceeded before a successful call, a FailedToConnectError will be raised.\n            Must be non-negative.\n        :param retry_timeout: Time to wait between attempts to connect. Can also take a\n            Callable that takes the number of attempts so far, beginning at 0, and returns an int\n            or float to be passed to time.sleep.\n        :type retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1\n        :param int _attempts: Parameter used to keep track of the number of attempts in calling the\n            connect function across recursive calls. Passed as an argument to retry_timeout if it\n            is a Callable. This parameter should not be set by the initial caller.\n        :raises dbt.exceptions.FailedToConnectError: Upon exhausting all retry attempts without\n            successfully acquiring a handle.\n        :return: The given connection with its appropriate state and handle attributes set\n            depending on whether we successfully acquired a handle or not.\n        \"\"\"\n        timeout = retry_timeout(_attempts) if callable(retry_timeout) else retry_timeout\n        if timeout < 0:\n            raise dbt.exceptions.FailedToConnectError(\n                \"retry_timeout cannot be negative or return a negative time.\"\n            )\n    \n        if retry_limit < 0 or retry_limit > sys.getrecursionlimit():\n            # This guard is not perfect others may add to the recursion limit (e.g. built-ins).\n            connection.handle = None\n            connection.state = ConnectionState.FAIL\n            raise dbt.exceptions.FailedToConnectError(\"retry_limit cannot be negative\")\n    \n        try:\n            connection.handle = connect()\n            connection.state = ConnectionState.OPEN\n            return connection\n    \n        except tuple(retryable_exceptions) as e:\n            if retry_limit <= 0:\n                connection.handle = None\n                connection.state = ConnectionState.FAIL\n                raise dbt.exceptions.FailedToConnectError(str(e))\n    \n            logger.debug(\n                f\"Got a retryable error when attempting to open a {cls.TYPE} connection.\\n\"\n                f\"{retry_limit} attempts remaining. Retrying in {timeout} seconds.\\n\"\n                f\"Error:\\n{e}\"\n            )\n    \n            sleep(timeout)\n            return cls.retry_connection(\n                connection=connection,\n                connect=connect,\n                logger=logger,\n                retry_limit=retry_limit - 1,\n                retry_timeout=retry_timeout,\n                retryable_exceptions=retryable_exceptions,\n                _attempts=_attempts + 1,\n            )\n    \n        except Exception as e:\n            connection.handle = None\n            connection.state = ConnectionState.FAIL\n>           raise dbt.exceptions.FailedToConnectError(str(e))\nE           dbt.exceptions.FailedToConnectError: Database Error\nE             Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?database=integration_testing__1722521167148&output_format=JSON_Compact'\nE             For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/connections.py:271: FailedToConnectError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f53bdb5ed30>\nsql = 'macro create_schema'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n>           yield\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/firebolt/connections.py:148: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:1112: in execute_macro\n    result = macro_function(**kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:330: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:257: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:330: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:257: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:330: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:257: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:310: in execute\n    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch, limit=limit)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:138: in execute\n    _, cursor = self.add_query(sql, auto_begin)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:90: in add_query\n    return connection, cursor\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py:137: in __exit__\n    self.gen.throw(typ, value, traceback)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f53bdb5ed30>\nsql = \"\\n\\n      SELECT 'create_schema'\\n  \"\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n            yield\n        except Exception as e:\n            self.release()\n>           raise DbtRuntimeError(str(e))\nE           dbt.exceptions.DbtRuntimeError: Runtime Error\nE             Database Error\nE               Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?database=integration_testing__1722521167148&output_format=JSON_Compact'\nE               For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/firebolt/connections.py:151: DbtRuntimeError\n\nDuring handling of the above exception, another exception occurred:\n\nclean_up_logging = None\nproject_root = local('/tmp/pytest-of-runner/pytest-0/project63')\nprofiles_root = local('/tmp/pytest-of-runner/pytest-0/profile63')\nrequest = <SubRequest 'project' for <Function test_build_assert_equal>>\nunique_schema = 'public'\nprofiles_yml = {'test': {'outputs': {'default': {'account_name': 'automation', 'api_endpoint': 'api.staging.firebolt.io', 'client_id': 'mrWFcIhFtkxKd5fLm40MrRp7rDuZBBZ0', 'client_secret': SecretStr('**********'), ...}}, 'target': 'default'}}\ndbt_project_yml = {'flags': {'send_anonymous_usage_stats': False}, 'name': 'test', 'profile': 'test'}\npackages_yml = None, dependencies_yml = None, selectors_yml = None\nadapter = <dbt.adapters.firebolt.impl.FireboltAdapter object at 0x7f53bca2e4c0>\nproject_files = None\nshared_data_dir = '/home/runner/work/dbt-firebolt/dbt-firebolt/tests/data'\ntest_data_dir = '/home/runner/work/dbt-firebolt/dbt-firebolt/tests/functional/adapter/utils/data'\nlogs_dir = '/home/runner/work/dbt-firebolt/dbt-firebolt/logs/test17225226969354263302'\ntest_config = {}\n\n    @pytest.fixture(scope=\"class\")\n    def project(\n        clean_up_logging,\n        project_root,\n        profiles_root,\n        request,\n        unique_schema,\n        profiles_yml,\n        dbt_project_yml,\n        packages_yml,\n        dependencies_yml,\n        selectors_yml,\n        adapter,\n        project_files,\n        shared_data_dir,\n        test_data_dir,\n        logs_dir,\n        test_config,\n    ):\n        # Logbook warnings are ignored so we don't have to fork logbook to support python 3.10.\n        # This _only_ works for tests in `tests/` that use the project fixture.\n        warnings.filterwarnings(\"ignore\", category=DeprecationWarning, module=\"logbook\")\n        log_flags = Namespace(\n            LOG_PATH=logs_dir,\n            LOG_FORMAT=\"json\",\n            LOG_FORMAT_FILE=\"json\",\n            USE_COLORS=False,\n            USE_COLORS_FILE=False,\n            LOG_LEVEL=\"info\",\n            LOG_LEVEL_FILE=\"debug\",\n            DEBUG=False,\n            LOG_CACHE_EVENTS=False,\n            QUIET=False,\n            LOG_FILE_MAX_BYTES=1000000,\n        )\n        setup_event_logger(log_flags)\n        orig_cwd = os.getcwd()\n        os.chdir(project_root)\n        # Return whatever is needed later in tests but can only come from fixtures, so we can keep\n        # the signatures in the test signature to a minimum.\n        project = TestProjInfo(\n            project_root=project_root,\n            profiles_dir=profiles_root,\n            adapter_type=adapter.type(),\n            test_dir=request.fspath.dirname,\n            shared_data_dir=shared_data_dir,\n            test_data_dir=test_data_dir,\n            test_schema=unique_schema,\n            database=adapter.config.credentials.database,\n            test_config=test_config,\n        )\n        project.drop_test_schema()\n>       project.create_test_schema()\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/fixtures/project.py:524: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/fixtures/project.py:440: in create_test_schema\n    self.adapter.create_schema(relation)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/impl.py:164: in create_schema\n    self.execute_macro(CREATE_SCHEMA_MACRO_NAME, kwargs=kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:1112: in execute_macro\n    result = macro_function(**kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py:137: in __exit__\n    self.gen.throw(typ, value, traceback)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f53bdb5ed30>\nsql = 'macro create_schema'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n            yield\n        except Exception as e:\n            self.release()\n>           raise DbtRuntimeError(str(e))\nE           dbt.exceptions.DbtRuntimeError: Runtime Error\nE             Runtime Error\nE               Database Error\nE                 Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?database=integration_testing__1722521167148&output_format=JSON_Compact'\nE                 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/firebolt/connections.py:151: DbtRuntimeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"shared_data_dir","time":{"start":1722521282561,"stop":1722521282561,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmpdir_factory","time":{"start":1722521282561,"stop":1722521282561,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"test_data_dir","time":{"start":1722522555006,"stop":1722522555006,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"project_root","time":{"start":1722522695966,"stop":1722522695967,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clean_up_logging","time":{"start":1722522695966,"stop":1722522695966,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"profiles_root","time":{"start":1722522695967,"stop":1722522695968,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dbt_profile_target","time":{"start":1722522695968,"stop":1722522695968,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dbt_profile_data","time":{"start":1722522695968,"stop":1722522695968,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"unique_schema","time":{"start":1722522695968,"stop":1722522695968,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"profiles_config_update","time":{"start":1722522695968,"stop":1722522695968,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"profiles_yml","time":{"start":1722522695968,"stop":1722522695969,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"prefix","time":{"start":1722522695968,"stop":1722522695968,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dbt_project_yml","time":{"start":1722522695969,"stop":1722522695970,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"project_config_update","time":{"start":1722522695969,"stop":1722522695969,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dependencies","time":{"start":1722522695970,"stop":1722522695970,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"selectors","time":{"start":1722522695970,"stop":1722522695970,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"adapter","time":{"start":1722522695970,"stop":1722522696401,"duration":431},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"packages","time":{"start":1722522695970,"stop":1722522695970,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"selectors_yml","time":{"start":1722522695970,"stop":1722522695970,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"dependencies_yml","time":{"start":1722522695970,"stop":1722522695970,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"packages_yml","time":{"start":1722522695970,"stop":1722522695970,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"analyses","time":{"start":1722522696401,"stop":1722522696401,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"properties","time":{"start":1722522696401,"stop":1722522696401,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"models","time":{"start":1722522696401,"stop":1722522696401,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"snapshots","time":{"start":1722522696401,"stop":1722522696401,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tests","time":{"start":1722522696401,"stop":1722522696401,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"seeds","time":{"start":1722522696401,"stop":1722522696401,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"macros","time":{"start":1722522696401,"stop":1722522696401,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"logs_dir","time":{"start":1722522696402,"stop":1722522696402,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"test_config","time":{"start":1722522696402,"stop":1722522696402,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"project_files","time":{"start":1722522696402,"stop":1722522696402,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"project","time":{"start":1722522696403,"stop":1722522699017,"duration":2614},"status":"broken","statusMessage":"dbt.exceptions.DbtRuntimeError: Runtime Error\n  Runtime Error\n    Database Error\n      Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?database=integration_testing__1722521167148&output_format=JSON_Compact'\n      For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/fixtures/project.py\", line 524, in project\n    project.create_test_schema()\n  File \"/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/fixtures/project.py\", line 440, in create_test_schema\n    self.adapter.create_schema(relation)\n  File \"/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/impl.py\", line 164, in create_schema\n    self.execute_macro(CREATE_SCHEMA_MACRO_NAME, kwargs=kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py\", line 1112, in execute_macro\n    result = macro_function(**kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py\", line 137, in __exit__\n    self.gen.throw(typ, value, traceback)\n  File \"/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/firebolt/connections.py\", line 151, in exception_handler\n    raise DbtRuntimeError(str(e))\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"seeds","time":{"start":1722522699755,"stop":1722522699755,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"macros","time":{"start":1722522709069,"stop":1722522709069,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"dbt.exceptions.DbtRuntimeError: Runtime Error\n  Runtime Error\n    Database Error\n      Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?database=integration_testing__1722521167148&output_format=JSON_Compact'\n      For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502","statusTrace":"cls = <class 'dbt.adapters.firebolt.connections.FireboltConnectionManager'>\nconnection = Connection(type='firebolt', name='_test', state=<ConnectionState.CLOSED: 'closed'>, transaction_open=False, _handle=No...'com.firebolt.FireboltDriver', engine_name='integration_testing__1722521167148', account_name='automation', retries=1))\nconnect = <function FireboltConnectionManager.open.<locals>.connect at 0x7f53bc6b2c10>\nlogger = AdapterLogger(name='Firebolt')\nretryable_exceptions = [<class 'firebolt.utils.exception.FireboltDatabaseError'>, <class 'firebolt.utils.exception.ConnectionError'>, <class 'firebolt.utils.exception.InterfaceError'>]\nretry_limit = 1, retry_timeout = 1, _attempts = 0\n\n    @classmethod\n    def retry_connection(\n        cls,\n        connection: Connection,\n        connect: Callable[[], AdapterHandle],\n        logger: AdapterLogger,\n        retryable_exceptions: Iterable[Type[Exception]],\n        retry_limit: int = 1,\n        retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1,\n        _attempts: int = 0,\n    ) -> Connection:\n        \"\"\"Given a Connection, set its handle by calling connect.\n    \n        The calls to connect will be retried up to retry_limit times to deal with transient\n        connection errors. By default, one retry will be attempted if retryable_exceptions is set.\n    \n        :param Connection connection: An instance of a Connection that needs a handle to be set,\n            usually when attempting to open it.\n        :param connect: A callable that returns the appropiate connection handle for a\n            given adapter. This callable will be retried retry_limit times if a subclass of any\n            Exception in retryable_exceptions is raised by connect.\n        :type connect: Callable[[], AdapterHandle]\n        :param AdapterLogger logger: A logger to emit messages on retry attempts or errors. When\n            handling expected errors, we call debug, and call warning on unexpected errors or when\n            all retry attempts have been exhausted.\n        :param retryable_exceptions: An iterable of exception classes that if raised by\n            connect should trigger a retry.\n        :type retryable_exceptions: Iterable[Type[Exception]]\n        :param int retry_limit: How many times to retry the call to connect. If this limit\n            is exceeded before a successful call, a FailedToConnectError will be raised.\n            Must be non-negative.\n        :param retry_timeout: Time to wait between attempts to connect. Can also take a\n            Callable that takes the number of attempts so far, beginning at 0, and returns an int\n            or float to be passed to time.sleep.\n        :type retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1\n        :param int _attempts: Parameter used to keep track of the number of attempts in calling the\n            connect function across recursive calls. Passed as an argument to retry_timeout if it\n            is a Callable. This parameter should not be set by the initial caller.\n        :raises dbt.exceptions.FailedToConnectError: Upon exhausting all retry attempts without\n            successfully acquiring a handle.\n        :return: The given connection with its appropriate state and handle attributes set\n            depending on whether we successfully acquired a handle or not.\n        \"\"\"\n        timeout = retry_timeout(_attempts) if callable(retry_timeout) else retry_timeout\n        if timeout < 0:\n            raise dbt.exceptions.FailedToConnectError(\n                \"retry_timeout cannot be negative or return a negative time.\"\n            )\n    \n        if retry_limit < 0 or retry_limit > sys.getrecursionlimit():\n            # This guard is not perfect others may add to the recursion limit (e.g. built-ins).\n            connection.handle = None\n            connection.state = ConnectionState.FAIL\n            raise dbt.exceptions.FailedToConnectError(\"retry_limit cannot be negative\")\n    \n        try:\n>           connection.handle = connect()\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/connections.py:241: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/firebolt/connections.py:121: in connect\n    handle = sdk_connect(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/connection.py:56: in connect\n    return connect_v2(\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/connection.py:139: in connect_v2\n    cursor.execute(f\"USE DATABASE {database}\")\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/common/base_cursor.py:122: in inner\n    return func(self, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:239: in execute\n    self._do_execute(query, params_list, skip_parsing)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:188: in _do_execute\n    self._raise_if_error(resp)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/firebolt/db/cursor.py:110: in _raise_if_error\n    resp.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Response [502 Bad Gateway]>\n\n    def raise_for_status(self) -> Response:\n        \"\"\"\n        Raise the `HTTPStatusError` if one occurred.\n        \"\"\"\n        request = self._request\n        if request is None:\n            raise RuntimeError(\n                \"Cannot call `raise_for_status` as the request \"\n                \"instance has not been set on this response.\"\n            )\n    \n        if self.is_success:\n            return self\n    \n        if self.has_redirect_location:\n            message = (\n                \"{error_type} '{0.status_code} {0.reason_phrase}' for url '{0.url}'\\n\"\n                \"Redirect location: '{0.headers[location]}'\\n\"\n                \"For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/{0.status_code}\"\n            )\n        else:\n            message = (\n                \"{error_type} '{0.status_code} {0.reason_phrase}' for url '{0.url}'\\n\"\n                \"For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/{0.status_code}\"\n            )\n    \n        status_class = self.status_code // 100\n        error_types = {\n            1: \"Informational response\",\n            3: \"Redirect response\",\n            4: \"Client error\",\n            5: \"Server error\",\n        }\n        error_type = error_types.get(status_class, \"Invalid status code\")\n        message = message.format(self, error_type=error_type)\n>       raise HTTPStatusError(message, request=request, response=self)\nE       httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?database=integration_testing__1722521167148&output_format=JSON_Compact'\nE       For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/httpx/_models.py:761: HTTPStatusError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f53bdb5ed30>\nsql = \"\\n\\n      SELECT 'create_schema'\\n  \"\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n>           yield\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/firebolt/connections.py:148: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:79: in add_query\n    cursor = connection.handle.cursor()\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/contracts/connection.py:90: in handle\n    self._handle.resolve(self)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/contracts/connection.py:114: in resolve\n    return self.opener(connection)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/firebolt/connections.py:137: in open\n    return cls.retry_connection(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'dbt.adapters.firebolt.connections.FireboltConnectionManager'>\nconnection = Connection(type='firebolt', name='_test', state=<ConnectionState.CLOSED: 'closed'>, transaction_open=False, _handle=No...'com.firebolt.FireboltDriver', engine_name='integration_testing__1722521167148', account_name='automation', retries=1))\nconnect = <function FireboltConnectionManager.open.<locals>.connect at 0x7f53bc6b2c10>\nlogger = AdapterLogger(name='Firebolt')\nretryable_exceptions = [<class 'firebolt.utils.exception.FireboltDatabaseError'>, <class 'firebolt.utils.exception.ConnectionError'>, <class 'firebolt.utils.exception.InterfaceError'>]\nretry_limit = 1, retry_timeout = 1, _attempts = 0\n\n    @classmethod\n    def retry_connection(\n        cls,\n        connection: Connection,\n        connect: Callable[[], AdapterHandle],\n        logger: AdapterLogger,\n        retryable_exceptions: Iterable[Type[Exception]],\n        retry_limit: int = 1,\n        retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1,\n        _attempts: int = 0,\n    ) -> Connection:\n        \"\"\"Given a Connection, set its handle by calling connect.\n    \n        The calls to connect will be retried up to retry_limit times to deal with transient\n        connection errors. By default, one retry will be attempted if retryable_exceptions is set.\n    \n        :param Connection connection: An instance of a Connection that needs a handle to be set,\n            usually when attempting to open it.\n        :param connect: A callable that returns the appropiate connection handle for a\n            given adapter. This callable will be retried retry_limit times if a subclass of any\n            Exception in retryable_exceptions is raised by connect.\n        :type connect: Callable[[], AdapterHandle]\n        :param AdapterLogger logger: A logger to emit messages on retry attempts or errors. When\n            handling expected errors, we call debug, and call warning on unexpected errors or when\n            all retry attempts have been exhausted.\n        :param retryable_exceptions: An iterable of exception classes that if raised by\n            connect should trigger a retry.\n        :type retryable_exceptions: Iterable[Type[Exception]]\n        :param int retry_limit: How many times to retry the call to connect. If this limit\n            is exceeded before a successful call, a FailedToConnectError will be raised.\n            Must be non-negative.\n        :param retry_timeout: Time to wait between attempts to connect. Can also take a\n            Callable that takes the number of attempts so far, beginning at 0, and returns an int\n            or float to be passed to time.sleep.\n        :type retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1\n        :param int _attempts: Parameter used to keep track of the number of attempts in calling the\n            connect function across recursive calls. Passed as an argument to retry_timeout if it\n            is a Callable. This parameter should not be set by the initial caller.\n        :raises dbt.exceptions.FailedToConnectError: Upon exhausting all retry attempts without\n            successfully acquiring a handle.\n        :return: The given connection with its appropriate state and handle attributes set\n            depending on whether we successfully acquired a handle or not.\n        \"\"\"\n        timeout = retry_timeout(_attempts) if callable(retry_timeout) else retry_timeout\n        if timeout < 0:\n            raise dbt.exceptions.FailedToConnectError(\n                \"retry_timeout cannot be negative or return a negative time.\"\n            )\n    \n        if retry_limit < 0 or retry_limit > sys.getrecursionlimit():\n            # This guard is not perfect others may add to the recursion limit (e.g. built-ins).\n            connection.handle = None\n            connection.state = ConnectionState.FAIL\n            raise dbt.exceptions.FailedToConnectError(\"retry_limit cannot be negative\")\n    \n        try:\n            connection.handle = connect()\n            connection.state = ConnectionState.OPEN\n            return connection\n    \n        except tuple(retryable_exceptions) as e:\n            if retry_limit <= 0:\n                connection.handle = None\n                connection.state = ConnectionState.FAIL\n                raise dbt.exceptions.FailedToConnectError(str(e))\n    \n            logger.debug(\n                f\"Got a retryable error when attempting to open a {cls.TYPE} connection.\\n\"\n                f\"{retry_limit} attempts remaining. Retrying in {timeout} seconds.\\n\"\n                f\"Error:\\n{e}\"\n            )\n    \n            sleep(timeout)\n            return cls.retry_connection(\n                connection=connection,\n                connect=connect,\n                logger=logger,\n                retry_limit=retry_limit - 1,\n                retry_timeout=retry_timeout,\n                retryable_exceptions=retryable_exceptions,\n                _attempts=_attempts + 1,\n            )\n    \n        except Exception as e:\n            connection.handle = None\n            connection.state = ConnectionState.FAIL\n>           raise dbt.exceptions.FailedToConnectError(str(e))\nE           dbt.exceptions.FailedToConnectError: Database Error\nE             Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?database=integration_testing__1722521167148&output_format=JSON_Compact'\nE             For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/connections.py:271: FailedToConnectError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f53bdb5ed30>\nsql = 'macro create_schema'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n>           yield\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/firebolt/connections.py:148: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:1112: in execute_macro\n    result = macro_function(**kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:330: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:257: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:330: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:257: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:330: in __call__\n    return self.call_macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/clients/jinja.py:257: in call_macro\n    return macro(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:768: in __call__\n    return self._invoke(arguments, autoescape)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:782: in _invoke\n    rv = self._func(*arguments)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/sandbox.py:394: in call\n    return __context.call(__obj, *args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jinja2/runtime.py:303: in call\n    return __obj(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:310: in execute\n    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch, limit=limit)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:138: in execute\n    _, cursor = self.add_query(sql, auto_begin)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:90: in add_query\n    return connection, cursor\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py:137: in __exit__\n    self.gen.throw(typ, value, traceback)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f53bdb5ed30>\nsql = \"\\n\\n      SELECT 'create_schema'\\n  \"\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n            yield\n        except Exception as e:\n            self.release()\n>           raise DbtRuntimeError(str(e))\nE           dbt.exceptions.DbtRuntimeError: Runtime Error\nE             Database Error\nE               Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?database=integration_testing__1722521167148&output_format=JSON_Compact'\nE               For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/firebolt/connections.py:151: DbtRuntimeError\n\nDuring handling of the above exception, another exception occurred:\n\nclean_up_logging = None\nproject_root = local('/tmp/pytest-of-runner/pytest-0/project63')\nprofiles_root = local('/tmp/pytest-of-runner/pytest-0/profile63')\nrequest = <SubRequest 'project' for <Function test_build_assert_equal>>\nunique_schema = 'public'\nprofiles_yml = {'test': {'outputs': {'default': {'account_name': 'automation', 'api_endpoint': 'api.staging.firebolt.io', 'client_id': 'mrWFcIhFtkxKd5fLm40MrRp7rDuZBBZ0', 'client_secret': SecretStr('**********'), ...}}, 'target': 'default'}}\ndbt_project_yml = {'flags': {'send_anonymous_usage_stats': False}, 'name': 'test', 'profile': 'test'}\npackages_yml = None, dependencies_yml = None, selectors_yml = None\nadapter = <dbt.adapters.firebolt.impl.FireboltAdapter object at 0x7f53bca2e4c0>\nproject_files = None\nshared_data_dir = '/home/runner/work/dbt-firebolt/dbt-firebolt/tests/data'\ntest_data_dir = '/home/runner/work/dbt-firebolt/dbt-firebolt/tests/functional/adapter/utils/data'\nlogs_dir = '/home/runner/work/dbt-firebolt/dbt-firebolt/logs/test17225226969354263302'\ntest_config = {}\n\n    @pytest.fixture(scope=\"class\")\n    def project(\n        clean_up_logging,\n        project_root,\n        profiles_root,\n        request,\n        unique_schema,\n        profiles_yml,\n        dbt_project_yml,\n        packages_yml,\n        dependencies_yml,\n        selectors_yml,\n        adapter,\n        project_files,\n        shared_data_dir,\n        test_data_dir,\n        logs_dir,\n        test_config,\n    ):\n        # Logbook warnings are ignored so we don't have to fork logbook to support python 3.10.\n        # This _only_ works for tests in `tests/` that use the project fixture.\n        warnings.filterwarnings(\"ignore\", category=DeprecationWarning, module=\"logbook\")\n        log_flags = Namespace(\n            LOG_PATH=logs_dir,\n            LOG_FORMAT=\"json\",\n            LOG_FORMAT_FILE=\"json\",\n            USE_COLORS=False,\n            USE_COLORS_FILE=False,\n            LOG_LEVEL=\"info\",\n            LOG_LEVEL_FILE=\"debug\",\n            DEBUG=False,\n            LOG_CACHE_EVENTS=False,\n            QUIET=False,\n            LOG_FILE_MAX_BYTES=1000000,\n        )\n        setup_event_logger(log_flags)\n        orig_cwd = os.getcwd()\n        os.chdir(project_root)\n        # Return whatever is needed later in tests but can only come from fixtures, so we can keep\n        # the signatures in the test signature to a minimum.\n        project = TestProjInfo(\n            project_root=project_root,\n            profiles_dir=profiles_root,\n            adapter_type=adapter.type(),\n            test_dir=request.fspath.dirname,\n            shared_data_dir=shared_data_dir,\n            test_data_dir=test_data_dir,\n            test_schema=unique_schema,\n            database=adapter.config.credentials.database,\n            test_config=test_config,\n        )\n        project.drop_test_schema()\n>       project.create_test_schema()\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/fixtures/project.py:524: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/tests/fixtures/project.py:440: in create_test_schema\n    self.adapter.create_schema(relation)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/sql/impl.py:164: in create_schema\n    self.execute_macro(CREATE_SCHEMA_MACRO_NAME, kwargs=kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/base/impl.py:1112: in execute_macro\n    result = macro_function(**kwargs)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py:137: in __exit__\n    self.gen.throw(typ, value, traceback)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <dbt.adapters.firebolt.connections.FireboltConnectionManager object at 0x7f53bdb5ed30>\nsql = 'macro create_schema'\n\n    @contextmanager\n    def exception_handler(self, sql: str) -> Generator:\n        try:\n            yield\n        except Exception as e:\n            self.release()\n>           raise DbtRuntimeError(str(e))\nE           dbt.exceptions.DbtRuntimeError: Runtime Error\nE             Runtime Error\nE               Database Error\nE                 Server error '502 Bad Gateway' for url 'https://01hzdxdxjqa9n6c07d5j51skep.api.us-east-1.staging.firebolt.io/?database=integration_testing__1722521167148&output_format=JSON_Compact'\nE                 For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/dbt/adapters/firebolt/connections.py:151: DbtRuntimeError","steps":[],"attachments":[{"uid":"5f19fa8a99955782","name":"log","source":"5f19fa8a99955782.txt","type":"text/plain","size":627},{"uid":"269ac7265df025f5","name":"stdout","source":"269ac7265df025f5.txt","type":"text/plain","size":65}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"logs_dir::0","time":{"start":1722522699311,"stop":1722522699311,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"adapter::0","time":{"start":1722522699312,"stop":1722522699313,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"profiles_yml::0","time":{"start":1722522699315,"stop":1722522699315,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests.functional.adapter.utils"},{"name":"suite","value":"test_utils"},{"name":"subSuite","value":"TestSafeCast"},{"name":"host","value":"fv-az1020-381"},{"name":"thread","value":"2190-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.functional.adapter.utils.test_utils"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"578ea9ee55bde58c.json","parameterValues":[]}